[
    // Proposition de coordination
    ["mais", "PRO_COORD"],
    ["ou", "PRO_COORD"],
    ["et", "PRO_COORD"],
    ["donc", "PRO_COORD"],
    ["or", "PRO_COORD"],
    ["ni", "PRO_COORD"],
    ["car", "PRO_COORD"],

    // Pronom relatifs
    ["qui", "PRO_REL"],
    ["que", "PRO_REL"],
    ["quoi", "PRO_REL"],
    ["dont", "PRO_REL"],
    ["où", "PRO_REL"],
    ["lequel", "PRO_REL"],
    ["duquel", "PRO_REL"],
    ["auquel", "PRO_REL"],
    ["lesquels", "PRO_REL"],
    ["desquels", "PRO_REL"],
    ["auxquels", "PRO_REL"],
    ["laquelle", "PRO_REL"],
    ["de laquelle", "PRO_REL"],
    ["à laquelle", "PRO_REL"],
    ["lesquelles", "PRO_REL"],
    ["desquelles", "PRO_REL"],
    ["auxquelles", "PRO_REL"],
    
    // Conjonction de subordination
    ["que", "CONJ_SUB"],
    ["comme", "CONJ_SUB"],
    ["lorsque", "CONJ_SUB"],
    ["puisque", "CONJ_SUB"],
    ["quand", "CONJ_SUB"],
    ["si", "CONJ_SUB"],
    ["quoi que", "CONJ_SUB"],
    ["quoi qu'", "CONJ_SUB"],

    // Preposition de temps
    ["avant", "PRE_TEMPS"],
    ["après", "PRE_TEMPS"],
    ["dès", "PRE_TEMPS"],
    ["depuis", "PRE_TEMPS"],
    ["pendant", "PRE_TEMPS"],
    ["jusqu’à", "PRE_TEMPS"],
    ["jusqu’au", "PRE_TEMPS"],
    ["jusqu’aux", "PRE_TEMPS"],
    ["à partir de", "PRE_TEMPS"],
    ["à partir d'", "PRE_TEMPS"],
    ["durant", "PRE_TEMPS"],
    ["sur le point de", "PRE_TEMPS"],
    ["sur le point d'", "PRE_TEMPS"],
    ["à compter de", "PRE_TEMPS"],
    ["à compter d'", "PRE_TEMPS"],
    ["lors de", "PRE_TEMPS"],
    ["lors d'", "PRE_TEMPS"],
    ["avant de", "PRE_TEMPS"],
    ["avant d'", "PRE_TEMPS"],
    
    // Preposition de lieu
    ["près dans", "PRE_LIEU"],
    ["à l’intérieur de", "PRE_LIEU"],
    ["à l’intérieur d'", "PRE_LIEU"],
    ["entre", "PRE_LIEU"],
    ["à travers", "PRE_LIEU"],
    ["auprès de", "PRE_LIEU"],
    ["auprès d'", "PRE_LIEU"],
    ["chez", "PRE_LIEU"],
    ["contre", "PRE_LIEU"],
    ["là", "PRE_LIEU"],
    ["derrière", "PRE_LIEU"],
    ["devant", "PRE_LIEU"],
    ["hors", "PRE_LIEU"],
    ["parmi", "PRE_LIEU"],
    ["sous", "PRE_LIEU"],
    ["sur", "PRE_LIEU"],
    ["vers", "PRE_LIEU"],
    ["au-dessous de", "PRE_LIEU"],
    ["au-dessous d'", "PRE_LIEU"],
    ["au-dessus de", "PRE_LIEU"],
    ["au-dessus d'", "PRE_LIEU"],
    ["du côté de", "PRE_LIEU"],
    ["du côté d'", "PRE_LIEU"],
    ["en arrière de", "PRE_LIEU"],
    ["en arrière d'", "PRE_LIEU"],
    ["en bas de", "PRE_LIEU"],
    ["en bas d'", "PRE_LIEU"],
    ["en deçà de", "PRE_LIEU"],
    ["en deçà d'", "PRE_LIEU"],
    ["en dedans de", "PRE_LIEU"],
    ["en dedans d'", "PRE_LIEU"],
    ["en dehors de", "PRE_LIEU"],
    ["en dehors d'", "PRE_LIEU"],
    ["hors de", "PRE_LIEU"],
    ["hors d'", "PRE_LIEU"],
    ["loin de", "PRE_LIEU"],
    ["loin d'", "PRE_LIEU"],
    ["face à", "PRE_LIEU"],
    ["face aux", "PRE_LIEU"],
    ["au travers de", "PRE_LIEU"],
    ["au travers d'", "PRE_LIEU"],
    ["près de", "PRE_LIEU"],
    ["près d'", "PRE_LIEU"],
    
    // Preposition de cause
    ["à cause de", "PRE_CAUSE"],
    ["en raison de", "PRE_CAUSE"],
    
    // Preposition de but
    ["pour", "PRE_BUT"],
    ["en vue de", "PRE_BUT"],
    ["afin de", "PRE_BUT"],
    
    // Preposition de condition
    ["sauf", "PRE_CONDITION"],
    ["excepté", "PRE_CONDITION"],
    ["hormis", "PRE_CONDITION"],
    ["à condition que/qu'", "PRE_CONDITION"],
    ["dans le cas", "PRE_CONDITION"],
    ["à moins de", "PRE_CONDITION"],
    ["grâce à", "PRE_CONDITION"],
    ["concernant", "PRE_CONDITION"],
    ["moyennant", "PRE_CONDITION"],
    ["contrairement à", "PRE_CONDITION"],
    ["par manque de", "PRE_CONDITION"],
    
    // Preposition de manière
    ["sans", "PRE_MANIERE"],
    ["avec", "PRE_MANIERE"],
    ["par", "PRE_MANIERE"],
    ["comme", "PRE_MANIERE"],
    ["jusque", "PRE_MANIERE"],
    ["jusqu'à", "PRE_MANIERE"],
    ["jusqu'au", "PRE_MANIERE"],
    ["malgré", "PRE_MANIERE"],
    ["moins", "PRE_MANIERE"],
    ["selon", "PRE_MANIERE"],
    ["de manière à ", "PRE_MANIERE"],
    ["de façon à", "PRE_MANIERE"],
    ["de peur de", "PRE_MANIERE"],
    ["à force de", "PRE_MANIERE"],

    // Instants
    ["aujourd'hui", "PRE_TEMPS"],
    ["cette journée", "PRE_TEMPS"],
    ["ce jour", "PRE_TEMPS"],
    ["hier", "PRE_TEMPS"],
    ["avant-hier", "PRE_TEMPS"],
    ["demain", "PRE_TEMPS"],
    ["après-demain", "PRE_TEMPS"],
    ["matin", "PRE_TEMPS"],
    ["après-midi", "PRE_TEMPS"],
    ["soir", "PRE_TEMPS"],
    ["nuit", "PRE_TEMPS"],

    // Verbes exprimant l'impératif
    ["ordonner", "VER_IMP"],
    ["exiger", "VER_IMP"],
    ["vouloir", "VER_IMP"],
    ["devoir", "VER_IMP"],
    ["aimer", "VER_IMP"],
];