const french_categrorie = [
[   "INJURE", [
    "abruti", "aller chier dans sa caisse", "aller niquer sa mère", "aller se faire enculer", 
    "aller se faire endauffer", "aller se faire foutre", "aller se faire mettre", "andouille", 
    "appareilleuse", "assimilé", "astèque", "avorton", "bachi-bouzouk", "baleine", "bande d’abrutis", 
    "bâtard", "baudet", "beauf", "bellicole", "bête", "bête à pleurer", "bête comme ses pieds", 
    "bête comme un chou", "bête comme un cochon", "biatch", "bic", "bicot", "bicotte", "bite", 
    "bitembois", "bitembois", "bordille", "boucaque", "boudin", "bouffi", "bouffon", "bougnoul", 
    "bougnoule", "bougnoulie", "bougnoulisation", "bougnouliser", "bougre", "boukak", "boulet", 
    "bounioul", "bounioule", "bourdille", "bourricot", "branleur", "bridé", "bridée", "brigand", 
    "brise-burnes", "cacou", "cafre", "cageot", "caldoche", "casse-bonbon", "casse-couille", 
    "casse-couilles", "cave", "chagasse", "charlot de vogue", "chauffard", "chbeb", 
    "chien de chrétien", "chiennasse", "chienne", "chier", "chinetoc", "chinetoque", "chinetoque", 
    "chintok", "chleuh", "chnoque", "citrouille", "coche", "colon", "complotiste", "con", 
    "con comme la lune", "con comme ses pieds", "con comme un balai", "con comme un manche", 
    "con comme une chaise", "con comme une valise sans poignée", "conasse", "conchier", "connard", 
    "connarde", "connasse", "conspirationniste", "couille molle", "counifle", "courtaud", "cpf", 
    "crétin", "crevure", "cricri", "crotté", "crouillat", "crouille", "croûton", "débile", 
    "doryphore", "doxosophe", "doxosophie", "drouille", "du schnoc", "ducon", "duconnot", "dugenoux", 
    "dugland", "duschnock", "emmanché", "emmerder", "emmerdeur", "emmerdeuse", "empafé", "empapaouté", 
    "enculé", "enculé de ta race", "enculer", "enfant de putain", "enfant de pute", "enfant de salaud", 
    "enflure", "enfoiré", "envaselineur", "envoyer faire foutre", "épais", "espèce de", "espingoin", 
    "étron", "face de chien", "face de craie", "face de pet", "face de rat", "fachiste", "fdp", "fell", 
    "la ferme", "fermer sa gueule", "fils de bâtard", "fils de chien", "fils de chienne", 
    "fils de garce", "fils de pute", "fils de ta race", "fiotte", "folle", "fouteur", "fripouille", 
    "frisé", "fritz", "fritz", "fumier", "gaouri", "garage à bite", "garce", "gaupe", "gdm", "gland", 
    "glandeur", "glandeuse", "glandouillou", "glandu", "gnoul", "gnoule", "godon", "gogol", "goï", 
    "gook", "gouilland", "gouine", "gourdasse", "gourde", "gourgandine", "grognasse", "gueniche", 
    "guide de merde", "guindoule", "gwer", "habitant", "halouf", "imbécile", "incapable", 
    "islamo-gauchisme", "jean-foutre", "jean-fesse", "jeannette", "journalope", "kawish", "khmer rouge", 
    "khmer vert", "kikoo", "kikou", "kraut", "la fermer", "lâche", "lâcheux", "lavette", "lopette", 
    "magot", "makoumé", "mal blanchi", "manche", "mange-merde", "mangeux de marde", "marchandot", 
    "margouilliste", "marsouin", "mauviette", "melon", "mercon", "merdaille", "merdaillon", "merde", 
    "merdeux", "merdouillard", "michto", "minable", "minus", "misérable", "moinaille", "moins-que-rien", 
    "mollusque", "monacaille", "mongol", "mongol à batteries", "moricaud", "mort aux vaches", "morue", 
    "moule à gaufres", "moule à merde", "mouloud", "muzz", "naze", "nazi", "négro", "nez de bœuf", "niac", 
    "niafou", "niaiseux", "niakoué", "nique sa mère", "nique ta mère", "niquer", "niquer sa mère", 
    "nodocéphale", "nœud", "noob", "nord-phocéen", "ntm", "nul", "nulle", "orchidoclaste", "ordure", 
    "ortho", "pakos", "panoufle", "patarin", "pd", "peau", "peau de fesse", "peau de vache", "pecque", 
    "pédale", "pédé", "pédoque", "pelle à merde", "péquenaud", "personnage de comédie", "petite bite", 
    "petite merde", "pignouf", "pignoufe", "pissou", "pithécanthrope", "pleutre", "plouc", "pochard", 
    "pompe à vélo", "porc", "porcas", "porcasse", "pouf", "pouffiasse", "poufiasse", "poulet", "poundé", 
    "pourriture", "punaise", "putain", "putain de ta race", "pute", "pute borgne", "putois", "raclure", 
    "raclure de bidet", "radoteur", "rat", "raté", "raton", "retourne aux asperges", "ripopée", "robespierrot", 
    "roi des cons", "rosbif", "roulure", "sac à foutre", "sac à merde", "sac à papier", "sagouin", "salaud", 
    "sale", "salop", "salope", "sans-couilles", "satrouille", "sauvage", "schbeb", "schlague", "schleu", 
    "schnock", "schnoque", "sent-la-pisse", "social-traître", "sorcière", "sottiseux", "sous-merde", "stéarique", 
    "ta bouche", "ta gueule", "ta mère", "ta mère la pute", "ta race", "ta yeule", "tache", "tafiole", 
    "tantouserie", "tantouze", "tapette", "tapettitude", "tarlouze", "tata", "tebé", "tête carrée", 
    "tête de boche", "tête de cochon", "tête de gland", "tête de linotte", "tête de mule", "tête de nœud", 
    "tête de veau", "téteux", "teubé", "thénardier", "thon", "tocard", "traînée", "travail d’arabe", 
    "triple buse", "trou de cul", "trou du cul", "trouduc", "truiasse", "truie", "va te faire foutre", 
    "va te faire une soupe d’esques", "vaurien", "vendu", "vert-de-gris", "vide-couilles", "viédase", "vier", 
    "vieux", "vieux blanc", "vipère lubrique", "weeaboo", "xéropineur", "youd", "youp", "youpin", "youpine", 
    "youpinisation", "youtre", "zguègue", "insulte"]
],[
[   "ALIMENT", [
    "abats", "abricot", "actimel nature", "after-eight", "agar-agar", "agneau", "ail", "ail semoule", "alcool", 
    "algues", "céréales", "ananas", "anchois", "aneth", "anis étoilé / badiane", "arôme", "arrow-root", 
    "artichaut", "aspartame", "asperge", "aubergine", "autruche", "avocat", "baie de goji", "banane", "barre protéinée", 
    "basilic", "betterave", "beurre", "bicarbonate de soude", "bière", "bigorneau", "bio flan", "biscotte", 
    "biscuit", "biscuit aux céréales", "blanc d'oeuf en poudre", "blé (ebly)", "blette", "boeuf", "bonbon sans sucre", 
    "boudin blanc", "boudin noir", "bouillon de boeuf dégraissé", "bouillon de poule dégraissé", "boulgour", 
    "bresaola della valtellina", "brochet", "brocoli", "bulot", "cabillaud", "cacao dégraissé non sucré", "café", 
    "café soluble", "caille", "calmar", "camembert", "camembert 5%", "canard", "cancoillotte", "cannelle", "cantal", 
    "câpres", "cardamome", "carotte", "carré frais", "carré frais ail et fines herbes", "cassis", "céleri", "cerise", 
    "champagne", "champignon", "chapelure", "châtaigne", "chayotte", "cheddar", "cheval", "cheval", "chewing-gum sans sucre", 
    "chocolat noir", "chocolat van houten", "chou", "chou chinois", "chou romanesco", "chou rouge", "chou-fleur", 
    "choux de bruxelles", "ciboulette", "citron", "citron vert", "citronnelle", "citrouille", "clémentine", "clou de girofle", 
    "coca zéro", "coca-cola", "coeur de palmier", "coing", "colin", "colorant alimentaire", "complément alimentaire", 
    "compote de fruitse", "comté", "concentré de tomate", "concombre", "confiture allegée", "coque", "coquelet", "coriandre", 
    "corned beef", "cornichon", "côte de boeuf", "courge", "courge butternut", "courge spaghetti", "courgette", "crabe", 
    "crème d'avoine", "crème de soja", "crème fraîche", "crevette", "cuisses de grenouille", "cumin", "curcuma", "curry", 
    "danio", "daurade", "délice de saint agaune", "dinde", "dorade", "eau", "eau aromatisée", "eau gazeuse", "échalote", 
    "edam", "édulcorant", "églefin", "emmental", "endive", "entrecôte", "épinard", "escargot", "espadon", "estragon", "faisan", 
    "faisselle", "farine", "farine complète", "farine d'avoine", "farine de coco", "farine de lupin", "farine de sarrazin", 
    "farine de soja", "fenouil", "feuille de brick", "feuille de nori", "feuille de riz", "fève", "figue", "filet mignon fumé", 
    "flageolet", "flétan", "fleur d'oranger", "flocon d'avoine", "foie", "foie de veau", "foie de volaille", "fraise", 
    "framboise", "fromage", "fromage blanc", "fromage de rocroy", "fructose", "fruit sec", "galette de riz soufflé", "gambas", 
    "gaspacho", "gélatine", "gelée de madère", "gibier", "gingembre", "gluten de blé", "gomme de guar", "gouda", "gousse de vanille", 
    "graine de sésame", "graine de tournesol", "graine germée", "graines de chia", "gruyère", "gruyère", "hareng", "haricot blanc", 
    "haricot rouge", "haricot vert", "harissa", "herbes de provence", "homard", "huile", "huile d'olive", "huile de paraffine", 
    "huitre", "jambon cru", "jambon dégraissé", "jus d'orange", "kaki", "ketchup", "kiwi", "konjac", "kumquat", "lait de coco", 
    "lait de soja", "lait demi-écrémé", "lait écrémé", "lait écrémé en poudre", "lait écrémé fermenté", "lait entier", "langouste", 
    "langoustine", "lapin", "laurier", "lentille", "levure", "levure boulangère", "levure de bière", "lieu", "limande", "litchi", 
    "lotte", "loup de mer", "mâche", "maïs", "maïzena", "mangue", "maquereau", "margarine", "marron", "melon", "menthe", "merguez", 
    "merlu", "miel", "mimolette", "mirabelle", "morbier", "morue", "moule", "moutarde", "moutarde à l'ancienne", "mouton", "mûre", 
    "muscade", "myrtille", "navet", "nem", "noisette", "noix", "noix de coco", "noix de muscade", "noix de saint jacques", "oeuf", 
    "oeuf de caille", "oeuf de lump", "oie", "oignon", "olive", "orange", "orangina", "origan", "oursin", "pain", "pain azyme", 
    "pain complet", "pain de mie", "palourde", "pamplemousse", "panais", "papaye", "paprika", "parmesan", "pastèque", "pastrami", 
    "patate douce", "pâtes", "pâtisson", "pêche", "perche", "persil", "petit pois", "petit suisse", "pigeon", "piment", 
    "piment d'esplette", "pintade", "poire", "poireau", "pois cassé", "pois chiche", "pois gourmand", "pois sec", "poisson pané", 
    "poivre", "poivron", "polenta", "pomme", "pomme de terre", "pop corn", "porc", "port salut", "potimarron", "potiron", "poulet", 
    "poulpe", "pousse de bambou", "pousse de soja", "protéines de soja", "protifar", "prune", "pruneau", "psyllium", "pyrénées", 
    "quenelle", "quinoa", "quorn", "radis", "raifort", "raisin", "reblochon", "rhubarbe", "ricoré", "riz blanc", "riz complet", 
    "rognon", "rognon de veau", "romarin", "roquefort", "rôti de porc", "rouget", "rouleau de printemps", "roussette", "rumsteak", 
    "rutabaga", "safran", "saint-pierre", "salade", "salade frisée", "salsifi", "sandre", "sardine", "sauce nuoc-mâm", "sauce soja", 
    "sauce soja sucrée", "sauce teriyaki", "saucisse de soja", "saucisse de strasbourg", "saucisse de volaille", "saumon", "saumon fumé", 
    "savora", "schweppes", "seiche", "seitan", "sel", "semoule", "sirop", "sirop d'agave", "sole", "son d'avoine", "son d'épeautre", 
    "son de blé", "st nectaire", "st paulin", "steak de soja", "steak haché", "stévia", "sucre blanc", "sucre roux", "surimi", 
    "tabasco", "taillefine 0.9%", "taillefine fizz", "tapioca", "tempeh", "thé", "thon", "thym", "tisane", "tisane richter", "tofu", 
    "tofu soyeux", "tomate", "tomme de savoie", "tomme de savoie 10%", "topinambour", "tourteau", "truite", "truite saumonée", "turbot", 
    "vache qui rit", "veau", "vermicelle", "vermicelles de soja", "viande des grisons", "viandox", "vin blanc", "vin rouge", "vinaigre", 
    "vinaigre balsamique", "wazabi", "xylitol", "yaourt", "yaourt aux fruits", "yaourt aromatisé", "yaourt soja nature", "zeste d'agrume", 
    "zeste d'orange", "zeste de citron", "fruits frais", "fruit frais", "fruits secs", "fruit sec", "légumes", "légume", "ogéalineux", 
    "féculents", "charcuterie", "oeuf", "poisson", "mollusques", "mollusque", "crustacés", "crustacé", "viande", "volaille", "dessert", 
    "fromages", "fromage", "lait", "produits laitiers", "produit laitier", "beurre", "huiles végétales", "huile végétale", "margarine", 
    "crème fraîche", "condiments", "contiment", "produits sucrés", "produit sucré", "produits gras", "produit gras", "boisson", "soda", 
    "jus de fruits", "sel", "sucre", ]
],[
    "SPORT", [
    "athlétisme", "marche", "marathon", "course de fond", "demi-fond", "course d'obstacles", "sprint", "course de relais", "lancer du disque", 
    "lancer du javelot", "lancer du marteau", "lancer du poids", "saut en longueur", "saut en hauteur", "saut à la perche", "triple saut", 
    "décathlon", "heptathlon", "sport collectif", "balai-ballon sur glace", "balle au tambourin", "ballon au poing", "bandy", "baseball", 
    "basket-ball", "beach volley", "beach soccer", "bouzkachi", "calcio florentin", "camogie", "cricket", "crosse", "crosse ancienne", 
    "curling", "floorball", "football (ou soccer)", "football américain", "football australien", "football canadien", "football en salle", 
    "football gaélique", "jorkyball", "handball", "hockey en salle", "hockey subaquatique", "hockey sur gazon", "hockey sur glace", 
    "horse-ball", "hurling", "kinball", "korfball", "longue paume", "moto-ball", "netball", "paintball", "pelota p'urhépecha", "pelote basque", 
    "pesäpallo", "polo", "ringuette", "rink-hockey", "roller in line hockey", "rounder", "rugby à sept", "rugby à xv", "rugby à xiii", 
    "sepak takraw", "shinty", "slamball", "softball", "stoolball", "street-hockey", "tchoukball", "touch rugby", "town ball", "ultimate", 
    "unihockey (floorball)", "vigoro", "volley-ball", "volata", "water polo", "gymnastique", "acrosport", "aérobic", "gymnastique artistique", 
    "gymnastique rythmique", "trampoline", "tumbling", "twirling bâton", "épreuve combinées", "triathlon", "pentathlon moderne", "unifight", 
    "sport mécanique", "compétition automobile", "formule 1", "gp2 series", "formule 3", "champcar", "indy racing league", "24 heures du mans", 
    "le mans series", "karting", "nascar", "dtm", "wrc (rallye)", "wtcc", "a1 grand prix", "fol'car", "autocross", "rallycross", "dragster", 
    "tractor pulling", "course de camions", "legends cars", "compétition motocycliste", "endurance moto", "enduro", "freestyle motocross", 
    "motocross", "supermotard", "moto sur glace", "trial", "speedway", "stunt", "vitesse moto", "compétition aéronautique", "moto-ball", 
    "motonautisme", "motoneige", "sports de raquette", "badminton", "jeu de paume", "padel", "peloc", "pelote basque", "racketlon", 
    "racquetball", "speed badminton", "speed-ball", "squash", "tennis", "tennis de table", "sports avec animaux", "agility", "obé rythmée", 
    "course camarguaise", "course de chameaux", "course de chars", "course de traîneaux", "sport hippique", "sports équestres", "amazone", 
    "attelage", "attelage de tradition", "concours complet", "doma vaquera", "dressage", "endurance", "équitation camargue", 
    "équitation islandaise", "équitation western", "horse-ball", "hunter", "oulak", "polo", "polocrosse", "pony games", "saut d'obstacles", 
    "ski joëring", "trec", "voltige en cercle", "sport ancien", "barres", "calcio florentin", "course de chars", "harpastum", "jeu de mail", 
    "longue paume", "pancrace", "pentathlon antique", "pugilat", "soule", "town ball", "volata", "cyclisme", "bmx", "cyclisme artistique", 
    "cyclisme sur piste", "cyclisme sur route", "cyclosport", "cycloball", "cyclo-cross", "cyclotourisme", "vélo tout terrain", "chain-bike", 
    "arts martiaux", "aïkido", "bando et banshay", "capoeira", "ju-jitsu (jujutsu)", "jiu-jitsu brésilien", "judo", "karaté", "kendo", 
    "kobudo", "krabi krabong", "muay-boran", "ninjutsu", "sumo", "taekwondo", "unifight", "viet vo dao", "wushu (kung fu)", "sports de combat", 
    "boxe", "boxe américaine", "full-contact", "boxe anglaise", "boxe birmane (lethwei)", "boxe française (savate)", "boxe thaïlandaise", 
    "kick-boxing américain", "kick-boxing japonais", "canne et bâton de combat", "escrime", "lutte", "brancaille", "gouren", "lutte bretonne", 
    "lutte gréco-romaine", "lutte libre", "lutte sénégalaise", "naban (lutte birmane)", "ssirum", "sambo", "sport chanbara", "unifight", 
    "sport de glace", "bandy", "bobsleigh", "curling", "hockey sur glace", "luge", "moto sur glace", "danse sur glace", "patinage artistique", 
    "patinage de vitesse", "short-track", "skeleton", "sports de force", "bodybuilding", "fitness", "force basque", "haltérophilie", "highland games", 
    "powerlifting", "tir à la corde", "sports de plein air et de nature", "alpinisme", "canyonisme", "course d'orientation", "décalade", "escalade", 
    "grimpe d'arbres", "pêche sportive", "raid nature", "spéléologie", "sport aérien", "aéromodélisme", "aérostation", "base jump", "cerf-volant", 
    "parachutisme", "parapente", "ulm", "vol libre", "vol à voile", "voltige aérienne", "vol moteur", "sports de cible", "ball-trap", "billards", 
    "billard américain", "billard anglais", "billard français", "snooker", "boule bretonne", "boulingrin", "boomerang", "bowling", "croquet", 
    "curling", "eisstock", "fléchettes", "golf", "jukskei", "paintball", "palets", "pétanque", "boule de fort", "quilles de neuf", "sarbacane", "tir", 
    "sarbacana", "sport boule (boule lyonnaise)", "tir", "tir à l'arc", "sport hybride", "football universel", "sport nautique", "apnée", "aviron", 
    "barque de sauvetage", "bateau-dragon", "canoë-kayak", "canyonisme", "char à voile", "dragon boat", "hockey subaquatique", "motomarine", 
    "joute nautique", "kayak-polo", "kitesurf", "nage avec palmes", "motonautisme", "natation", "natation synchronisée", "pêche sportive", 
    "planche à voile", "plongée sous-marine", "plongeon", "rafting", "rugby subaquatique", "ski nautique", "surf", "voile", "water polo", 
    "wakeboard", "sports de glisse", "ski", "biathlon", "combiné nordique", "saut à ski", "snowboard", "ski alpin", "ski acrobatique", 
    "ski freestyle", "ski de fond", "ski de vitesse", "ski sur herbe", "ski télémark", "nouveaux sports de glisse", "bodyboard", "freebord", 
    "kayak surf", "kiteski", "kitesnow", "kitesurf", "mountainboard", "roller", "skateboard", "snowboard", "streetboard", "surf", 
    "voile sur glace", "longskate", "speedcubing", "echecs", "footbag", "danse sportive", "main à main", "marche nordique", "parkour", 
    "sport stacking", "sport électronique"]
],[
    "ARBRE", [
    "abee","abees","abeille","abeilles","abelia","abelias","abelie","abelies","abies","abouta","aboutas","abricot","abricotier","abricotiers",
    "abricots","absinthe","absinthes","acacia","acacias","acajou","acajous","actinidia","actinidias","actinidie","actinidies","adragant","adragante",
    "adragantes","adragants","agonis","agrion","agrions","agui","aguis","aie","aies","aigrette","aigrettes","aigrin","aigrins","ailante","ailantes",
    "airas","aire","airelle","airelles","aires","ajonc","ajoncs","alaterne","alaternes","albergier","albergiers","albizzia","albizzias","aleurite",
    "aleurites","aliboufier","aliboufiers","alisier","alisiers","alizier","aliziers","allamanda","allamandas","allier","allouchier","allouchiers",
    "aloes","alouchier","alouchiers","alquifoux","altea","alteas","althea","altheas","althee","althees","amandier","amandiers","amarante","amarantes",
    "amarinas","amarine","amarines","amboine","amboines","ambrette","ambrettes","amelanchier","amelanchiers","ami","amis","amorphe","amorphes",
    "amourette","amourettes","ampelopsis","ana","anacarde","anacardes","anacardier","anacardiers","anas","andromede","andromedes","angelique",
    "angeliques","angustura","angusturas","angusture","angustures","anil","anils","anime","animes","anisette","anisettes","annone","annones",
    "annonier","annoniers","anona","anonas","anone","anones","anonier","anoniers","arabe","arabes","arabica","arabicas","arac","aracs","arak",
    "araks","aralia","aralias","araucaria","araucarias","arbois","arbousier","arbousiers","arec","arecs","arequier","arequiers","argan","arganier",
    "arganiers","argans","argousier","argousiers","armoise","armoises","arol","arole","aroles","arolle","arolles","arols","arquebuse","arquebuses",
    "artocarpe","artocarpes","artocarpus","aspic","aspics","assamela","assamelas","ataca","atacas","atoca","atocas","atocatier","atocatiers",
    "attier","attiers","aube","aubepine","aubepines","aubes","aubier","aubiers","aubois","aucuba","aucubas","augeron","augerons","aulne","aulnes",
    "aunai","aunais","aune","aunes","aveline","avelines","avelinier","aveliniers","avocat","avocatier","avocatiers","avocats","avodire","avodires",
    "awale","awales","ay","ays","azalee","azalees","azerolier","azeroliers","azobe","azobes","ba","bacchante","bacchantes","badamier","badamiers",
    "badiane","badianes","bagasse","bagasses","baguenaudier","baguenaudiers","baguier","baguiers","balai","balais","balanite","balanites","balata",
    "balatas","balsa","balsamier","balsamiers","balsas","ban","bancoul","bancoulier","bancouliers","bancouls","banian","banians","bans","baobab",
    "baobabs","bar","barboter","barbule","barbules","barigoule","barre","barres","bars","bas","bauhinia","bauhinias","bauhinie","bauhinies","baume",
    "baumes","baumier","baumiers","bec","becs","belladone","belladones","ben","benjoin","benjoins","bens","berberis","bergamotier","bergamotiers",
    "bergere","bergeres","bete","betel","betels","betes","bi","bibacier","bibaciers","bibasse","bibasses","bibassier","bibassiers","bigaradier",
    "bigaradiers","bigarrat","bigarreau","bigarreautier","bigarreautiers","bigarreaux","bignone","bignones","bignonia","bignonias","biolle","biolles",
    "bis","blasera","blaseras","bleu","bleuet","bleuetier","bleuetiers","bleuets","bleus","bluet","bluets","boa","boas","boire","boires","bois",
    "boisson","boissons","boldo","boldos","bombardier","bombardiers","bon","bonamia","bonamias","bons","borasse","borasses","borassus","bosse",
    "bosses","bouchon","bouchons","bouda","boudas","bougainvillee","bougainvillees","bougainvillier","bougainvilliers","bouillard","bouillards",
    "boule","bouleau","bouleaux","boules","bourdaine","bourdaines","bourrade","bourrades","bous","branle","branles","bresil","bresillet","bresillets",
    "bresils","breton","bretons","brimbelle","brimbelles","brosse","brossee","brossees","brosses","brou","brouillard","brouillards","brous","bru",
    "brugnon","brugnonier","brugnoniers","brugnons","bruis","brule","brules","brus","bruyere","bruyeres","bubinga","bubingas","bucher","buchers",
    "buddleia","buddleias","bugrane","bugranes","buis","bulle","bulles","busserole","busseroles","cacao","cacaos","cacaotier","cacaotiers",
    "cacaoyer","cacaoyers","cachou","cachous","cade","cades","cadra","cadras","cafe","cafeier","cafeiers","cafes","cailcedrat","cailcedrats",
    "caillebotte","caillebottes","cajeput","cajeputier","cajou","cajous","calamite","calamites","calebasse","calebasses","calebassier","calebassiers",
    "callune","callunes","calycanthe","calycanthes","calypso","calypsos","camelia","camelias","camellia","camellias","campeche","campeches",
    "camphre","camphres","camphrier","camphriers","canada","canadas","canari","canaris","canche","canches","caneficier","caneficiers","canneberge",
    "canneberges","cannelier","canneliers","cannelle","cannelles","canot","canots","caoutchouc","caoutchoucs","capelets","caprier","capriers",
    "carambole","caramboles","carambolier","caramboliers","carolin","caroline","carolines","carolins","caroube","caroubes","caroubier","caroubiers",
    "carouge","carouges","caryer","caryers","casse","casses","cassie","cassier","cassiers","cassies","cassine","cassines","cassis","cassissier",
    "cassissiers","casuarina","casuarinas","catalpa","catalpas","caverons","cedrat","cedratier","cedratiers","cedrats","cedre","cedres","cembro",
    "cembros","cenellier","cenelliers","cerisier","cerisiers","chamaerops","chamerops","chandelle","chandelles","change","changes","charme","charmes",
    "charmille","charmilles","chas","chasse","chasses","chat","chataigne","chataignes","chataignier","chataigniers","chats","chausse","chausses",
    "chene","cheneau","cheneaux","chenes","cherimole","cherimoles","cherimolier","cherimoliers","chevrefeuille","chevrefeuilles","chevrote",
    "chevrotes","chicot","chicots","china","chinas","chrysantheme","chrysanthemes","cinchona","cinchonas","cinnamome","cinnamomes","cipre","cipres",
    "cirier","ciriers","ciste","cistes","citron","citronnier","citronniers","citrons","citrus","civette","civettes","clematite","clematites",
    "clementinier","clementiniers","cleome","cleomes","cobaea","cobaeas","cobea","cobeas","cobee","cobees","coca","cocaier","cocaiers","cocas",
    "cochenille","cochenilles","coco","cocos","cocotier","cocotiers","cognassier","cognassiers","coing","coings","cola","colas","colatier","colatiers",
    "colletee","colletees","colonie","colonies","columelle","columelles","cone","cones","conga","congas","copahu","copahus","copaier","copaiers",
    "copal","copalier","copaliers","copals","copayer","copayers","cordyline","cordylines","core","cores","cormier","cormiers","corne","cornes",
    "corniot","corniots","cornouiller","cornouillers","cornus","coronille","coronilles","corossol","corossolier","corossoliers","corossols",
    "corroyere","corroyeres","cotelee","cotelees","cotelette","cotelettes","coton","cotoneaster","cotoneasters","cotonnier","cotonniers","cotons",
    "coudra","coudras","coudre","coudres","coudrette","coudrettes","coudrier","coudriers","coula","coulas","coumarou","coumarous","courbaril",
    "courbarils","courrouca","courroucas","coursier","coursiers","coutons","crataegus","croton","crotons","cryptomeria","cryptomerias","cubebe",
    "cubebes","curatelle","curatelles","cycas","cynorhodon","cynorhodons","cynorrhodon","cynorrhodons","cypres","cytise","cytises","daille",
    "dailles","dais","damas","daphne","daphnes","dattier","dattiers","de","deboule","deboules","des","deutzia","deutzias","doucain","doucains",
    "doucin","doucins","doudou","doudous","douglas","douleur","douleurs","doum","doums","doussie","doussies","dracaena","dracaenas","dracena",
    "dracenas","dragonnier","dragonniers","drelin","dryade","dryades","durian","durians","durion","durions","ebene","ebenes","ebenier","ebeniers",
    "eglantier","eglantiers","eglantine","eglantines","elaeis","eleis","elemi","elemis","embrevates","encens","ephedra","ephedras","epicea",
    "epiceas","epine","epines","epinette","epinettes","erable","erables","erythrine","erythrines","espere","esperes","eucalyptus","eupatoire",
    "eupatoires","euphorbe","euphorbes","fa","fan","fans","farigoule","farigoules","faro","faros","fatsia","fatsias","fayard","fayards","fee",
    "fees","feijoa","feijoas","feu","feus","feux","fevier","feviers","ficus","fie","fier","fiers","fies","fige","figes","figue","figues","figuier",
    "figuiers","filaire","filaires","filao","filaos","flamboyant","flamboyants","fol","forsythia","forsythias","fortunella","fortunellas","fou",
    "fougere","fougeres","fouie","fouies","fous","fouteau","fouteaux","foyard","foyards","fragon","fragons","frais","framboise","framboises",
    "framboisier","framboisiers","framire","framires","franc","francs","frangipane","frangipanes","frangipanier","frangipaniers","frelon","frelons",
    "frene","frenes","fretillons","frole","frolons","fromager","fromagers","fuchsia","fuchsias","fusain","fusains","fustet","fustets","gadellier",
    "gadelliers","gaiac","gaiacs","gainier","gainiers","gale","gales","garais","garas","gardenia","gardenias","garou","garous","gattilier",
    "gattiliers","gaulette","gaulettes","gaultheria","gaultherias","gaultherie","gaultheries","genet","genets","genevrier","genevriers","genievre",
    "genievres","germandree","germandrees","ginkgo","ginkgos","ginseng","ginsengs","girofle","girofles","giroflier","girofliers","gleditschia",
    "gleditschias","glu","glus","glycine","glycines","gommier","gommiers","gonakie","gonakier","gonakiers","gonakies","goyave","goyaves","goyavier",
    "goyaviers","gravelin","gravelins","grenade","grenades","grenadier","grenadiers","grenadille","grenadilles","grevillea","grevilleas","griffon",
    "griffons","griot","griots","griottier","griottiers","gripette","gripettes","grisard","grisards","gros","groseillier","groseilliers","gui",
    "guigne","guignes","guignier","guigniers","guis","guitare","guitares","hamamelis","haricot","haricots","hautbois","havi","havis","helichrysum",
    "helichrysums","henne","hennes","hetre","hetres","hevea","heveas","hibiscus","hickory","hickorys","hie","hies","hippophae","hippophaes",
    "hortensia","hortensias","hou","houp","houx","hydrangee","hydrangees","hysope","hysopes","icaque","icaques","icaquier","icaquiers","if","ifs",
    "illipe","illipes","indigo","indigos","indigotier","indigotiers","ipe","ipeca","ipecacuana","ipecacuanas","ipecacuanha","ipecacuanhas",
    "ipecas","ipes","ipomee","ipomees","iroko","irokos","ive","ives","jaborandi","jaborandis","jacapucayo","jacapucayos","jacaranda","jacarandas",
    "jacquier","jacquiers","jambose","jamboses","jambosier","jambosiers","jamerosier","jamerosiers","jan","jans","jaque","jaques","jaquier",
    "jaquiers","jasmin","jasmins","jojoba","jojobas","jujubier","jujubiers","kaki","kakis","kalmia","kalmias","kapok","kapokier","kapokiers",
    "kapoks","karite","karites","karkade","karkades","kava","kavas","kawa","kawas","kentia","kentias","kermes","kerria","kerrias","kerrie","kerries",
    "ketmie","ketmies","khat","khats","kiwi","kiwis","kola","kolas","kolatier","kolatiers","kore","kores","kumquat","kumquats","kuna","kunas",
    "labdanum","labdanums","ladanum","ladanums","lambrusque","lambrusques","lande","landes","landolphia","landolphias","landolphie","landolphies",
    "lantana","lantanas","lantanier","lantaniers","lapacho","lapachos","large","larges","larix","latanier","lataniers","laurier","lauriers","lavande",
    "lavandes","lavandin","lavandins","lawsonia","lawsonias","le","lentisque","lentisques","lepidodendron","lepidodendrons","lepta","les","letchi",
    "letchis","liard","liards","lichee","lichees","lie","liege","lieges","lierre","lierres","lies","lilas","limba","limbas","limbo","limbos","lime",
    "limequat","limequats","limes","limettier","limettiers","limon","limonier","limoniers","limons","liquidambar","liquidambars","lire","lires","litchi",
    "litchis","longane","longanes","longanier","longaniers","loque","loques","loranthus","lori","loris","los","lotier","lotiers","loure","loures",
    "luisette","luisettes","lychee","lychees","macadamia","macadamias","macassar","macassars","magnolia","magnolias","magnolier","magnoliers",
    "magot","magots","mahaleb","mahalebs","mahonia","mahonias","mai","mail","mails","mais","malherbe","malherbes","malpighie","malpighies","malus",
    "mammouth","mammouths","mana","manas","mancenillier","mancenilliers","mandarin","mandarine","mandarines","mandarinier","mandariniers","mandarins",
    "mangle","mangles","manglier","mangliers","mangoustan","mangoustanier","mangoustaniers","mangoustans","mangouste","mangoustes","mangoustier",
    "mangoustiers","mangue","mangues","manguier","manguiers","maniguette","maniguettes","manioc","maniocs","manzanilla","manzanillas","mara","maras",
    "marcotte","marcottes","margotte","margottes","margousier","margousiers","marmottier","marmottiers","marri","marris","marronnier","marronniers",
    "marsault","marsaults","marseau","marseaux","mat","mate","mates","mats","medicinier","mediciniers","meleze","melezes","melia","melias",
    "meranti","merantis","merbau","merbaux","merise","merises","merisier","merisiers","meuron","meurons","micocoulier","micocouliers","miconia",
    "miconias","migre","migres","millepertuis","mimosa","mimosas","mirabelle","mirabelles","mirabellier","mirabelliers","moisie","moisies",
    "mombin","mombins","moringa","moringas","mou","moue","moues","mourais","mous","murier","muriers","muron","murons","muscade","muscades","muscadier",
    "muscadiers","muscardin","muscardins","myrica","myricas","myrobalan","myrobalans","myrobolan","myrobolans","myroxyle","myroxyles","myroxylon",
    "myroxylons","myrrhe","myrrhes","myrte","myrtes","myrtille","myrtilles","myrtillier","myrtilliers","na","nagi","nagis","nard","nards","nashi",
    "nashis","natte","nattes","nattier","nattiers","neem","neems","neflier","nefliers","negondo","negondos","negrier","negriers","negundo",
    "negundos","neon","neons","nepenthes","nere","neres","nerprun","nerpruns","niangon","niangons","niaouli","niaoulis","nie","nies","noce",
    "noces","noisetier","noisetiers","nothofagus","noue","noues","noyer","noyers","nui","nuis","oba","obas","obeche","obeches","obier","obiers",
    "ode","odes","okoume","okoumes","oleandre","oleandres","oleastre","oleastres","oliban","olibans","olive","olives","olivet","olivets","olivette",
    "olivettes","olivier","oliviers","oranger","orangers","orme","ormeau","ormeaux","ormes","ormille","ormilles","orne","ornes","oserons","osier",
    "osiers","ou","ourle","ourles","pacane","pacanes","pacanier","pacaniers","paire","paires","paletuvier","paletuviers","palissandre",
    "palissandres","paliure","paliures","palme","palmes","palmette","palmettes","palmier","palmiers","palmiste","palmistes","pame","pames",
    "pamplemousse","pamplemousses","pamplemoussier","pamplemoussiers","panace","panaces","panax","pandanus","papayer","papayers","paquette",
    "paquettes","paradis","parasolier","parasoliers","parsi","parsis","passiflore","passiflores","patenotre","patenotres","paulownia","paulownias",
    "paumer","pavates","pavie","pavies","paya","payas","peche","pecher","pechers","peches","peket","pekets","pequet","pequets","perche","perches",
    "pere","peres","peri","perie","peries","peris","pesse","pesses","petrole","petroles","peu","peuple","peuples","peuplier","peupliers","phanere",
    "phaneres","phenix","philodendron","philodendrons","phlomis","phoenix","phytelephas","piassava","piassavas","pible","pieris","pignon","pignons",
    "pilocarpe","pilocarpes","piment","pimenta","pimentas","piments","pin","pinasse","pinasses","pinastre","pinastres","pincas","pine","pinede",
    "pinedes","pines","pinot","pinots","pins","pistachier","pistachiers","pitchpin","pitchpins","pittosporum","pittosporums","plantain","plantains",
    "plaqueminier","plaqueminiers","platane","platanes","pleine","pleines","plumbago","plumbagos","poinsettia","poinsettias","pointe","pointes",
    "poire","poires","poirier","poiriers","poissa","poissas","poisse","poisses","poivrier","poivriers","pomelo","pomelos","pommette","pommettes",
    "pommier","pommiers","pompon","pompons","pondeuse","pondeuses","pote","potes","pouilleux","poupe","poupes","preau","preaux","premier","premiers",
    "pris","promis","pruche","pruches","prune","prunellier","prunelliers","prunes","prunier","pruniers","prunus","prusse","prusses","pua","puas",
    "puine","puines","puna","punas","putain","putains","putier","putiers","putiet","putiets","pyracantha","pyracanthas","qat","qats","quai","quais",
    "quassia","quassias","quassier","quassiers","quebracho","quebrachos","quercitron","quercitrons","quetschier","quetschiers","quinine","quinines",
    "quinquina","quinquinas","rack","racks","raisinet","raisinets","rambour","rambours","ramboutan","ramboutans","raphia","raphias","rauwolfia",
    "rauwolfias","reaumur","redoul","redouls","reglisse","reglisses","reseda","resedas","resinier","resiniers","resolu","resolus","rhizophore",
    "rhizophores","rhododendron","rhododendrons","ricin","ricins","robine","robines","robinier","robiniers","robre","robres","robusta","robustas",
    "rocou","rocous","rocouyer","rocouyers","role","roles","romarin","romarins","ronce","ronces","rondelette","rondelettes","rondier","rondiers",
    "ronier","roniers","roquet","roquets","ros","rosa","rosage","rosages","rosas","rosier","rosiers","rotule","rotules","roule","roules","roumi",
    "roumis","rousseau","rousseaux","rouvre","rouvres","rubane","rubanes","sa","sabine","sabines","sablier","sabliers","safou","safous","safoutier",
    "safoutiers","sage","sages","sagou","sagous","sagoutier","sagoutiers","saignons","sainbois","saint","saints","sal","sala","salace","salaces",
    "salas","salingue","salingues","sals","salsepareille","salsepareilles","samba","sambas","same","sames","sandaraque","sandaraques","santal","santals",
    "santaux","santoline","santolines","sapelli","sapellis","sapin","sapine","sapineau","sapineaux","sapines","sapinette","sapinettes","sapins",
    "sapote","sapotes","sapotier","sapotiers","sapotille","sapotilles","sapotillier","sapotilliers","sappan","sappans","sarriette","sarriettes","sas",
    "sassafras","satin","satine","satines","satins","sauge","sauges","saule","saules","savonnier","savonniers","savouree","savourees","scopa","scopas",
    "seillon","seillons","sen","sene","senellier","senelliers","senes","sens","sentis","sequoia","sequoias","seringa","seringas","seringat","seringats",
    "serpentine","serpentines","serpolet","serpolets","sesbania","sesbanias","sesbanie","sesbanies","sida","sidas","sideroxylon","sideroxylons",
    "sigillaire","sigillaires","simaroube","simaroubes","simaruba","simarubas","sipo","sipos","skimmia","skimmias","smilax","sophora","sophoras",
    "sorbier","sorbiers","sou","sous","souveraine","souveraines","spiree","spirees","spondias","staphylier","staphyliers","steno","stenos","storax",
    "strychnee","strychnees","strychnos","styrax","sue","sues","sueur","sueurs","sumac","sumacs","sure","sureau","sureaux","sures","suret","surets",
    "surette","surettes","surin","surins","sus","sycomore","sycomores","symphonie","symphonies","symphorine","symphorines","ta","talipot","talipots",
    "tallipot","tallipots","tamarin","tamarinier","tamariniers","tamarins","tamaris","tamarix","tan","tans","tapure","tapures","tara","taras","taro",
    "taros","tas","tauzin","tauzins","taxaudier","taxaudiers","taxodier","taxodiers","taxodium","taxodiums","taxus","tchitola","tchitolas","te","teck",
    "tecks","teinturier","teinturiers","tek","teks","tel","tels","tenon","tenons","terebinthe","terebinthes","tes","the","theier","theiers","thes",
    "thuya","thuyas","thym","thyms","thymus","tilleul","tilleuls","tin","tins","toi","tola","tolas","tolu","tolus","tombe","tombes","tonca","toncas",
    "tonka","tonkas","tonnates","tot","tremblant","tremblants","tremble","trembles","trepas","tri","trifolium","trifoliums","tris","troene","troenes",
    "trogne","trognes","trompette","trompettes","trouille","trouilles","tsuga","tsugas","tulipier","tulipiers","turbina","turbinas","turbith","turbiths",
    "ugni","ugnis","upas","urceole","urceoles","vaccinier","vacciniers","vacoa","vacoas","vaine","vaines","valentine","valentines","vanillier",
    "vanilliers","vara","varan","varans","velani","velanis","ver","vergne","vergnes","vermillon","vermillons","verne","vernes","vernis","vers","vigne",
    "vigneau","vigneaux","vignes","vimes","vinaigrier","vinaigriers","viorne","viornes","virginie","virginies","virola","virolas","vis","vomiquier",
    "vomiquiers","wacapou","wacapous","washingtonia","washingtonias","weigelia","weigelias","wellingtonia","wellingtonias","wenge","wenges","wintergreen",
    "ximenia","ximenias","ximenie","ximenies","yeuse","yeuses","yohimbehe","yohimbehes","ypreau","ypreaux","yucca","yuccas","zamia","zamias","zamier",
    "zamiers","zelkova","zelkovas","zizyphe","zizyphes"]
    ],[
    "ANIMAL", [
    "ABALONE","ABALONES","ABLE","ABLES","ABLETTE","ABLETTES","ABONDANCE","ABONDANCES","ABYSSIN","ABYSSINS","ACALEPHE","ACALEPHES","ACCENTEUR",
    "ACCENTEURS","ACCIPITRIDE","ACCIPITRIDES","ACHATINE","ACHATINES","ACHIGAN","ACHIGANS","ACROBATE","ACROBATES","ACTINIE","ACTINIES","ACTINOPODE",
    "ACTINOPODES","ACTINOPTERYGIEN","ADA","ADAS","ADDAX","ADONIS","AEPYORNIS","AFRICAIN","AFRICAINS","AFRIKANER","AFRIKANERS","AGACE","AGACES",
    "AGAME","AGAMES","AGAMI","AGAMIDE","AGAMIDES","AGAMIS","AGASSE","AGASSES","AGLYPHE","AGLYPHES","AGNATHE","AGNATHES","AGNEAU","AGNEAUX",
    "AGNELET","AGNELETS","AGNELLE","AGNELLES","AGOUTI","AGOUTIS","AI","AIGLE","AIGLEFIN","AIGLEFINS","AIGLES","AIGLON","AIGLONNE","AIGLONNES",
    "AIGLONS","AIGNEL","AIGNELS","AIGREFIN","AIGREFINS","AIGRETTE","AIGRETTES","AIGUILLAT","AIGUILLATS","AINOU","AINOUS","AIREDALE","AIREDALES",
    "AIS","ALBACORE","ALBACORES","ALBATROS","ALBINOS","ALCIDE","ALCIDES","ALCIFORME","ALCIFORMES","ALCYON","ALCYONAIRE","ALCYONAIRES","ALCYONS",
    "ALERION","ALERIONS","ALEVIN","ALEVINS","ALEZAN","ALEZANS","ALGAZELLE","ALGAZELLES","ALIBORON","ALIBORONS","ALLACHE","ALLACHES","ALLIGATOR",
    "ALLIGATORS","ALLOSAURE","ALLOSAURES","ALOSE","ALOSES","ALOUATE","ALOUATES","ALOUETTE","ALOUETTES","ALPACA","ALPACAS","ALPAGA","ALPAGAS",
    "ALPAGUA","ALPAGUAS","ALYTE","ALYTES","AMADINE","AMADINES","AMAZONE","AMAZONES","AMBLYRHYNQUE","AMBLYRHYNQUES","AMBLYSTOME","AMBLYSTOMES",
    "AMBYSTOME","AMBYSTOMES","AMETHYSTE","AMETHYSTES","AMIBE","AMIBES","AMIE","AMIES","AMMODYTE","AMMODYTES","AMMONITE","AMMONITES","AMPHINEURE",
    "AMPHINEURES","AMPHIOXUS","AMPHIPODE","AMPHIPODES","AMPHIPRION","AMPHIPRIONS","AMPHIPTERE","AMPHIPTERES","AMPHISBENE","AMPHISBENES","AMPHIUME",
    "AMPHIUMES","AMPOULE","AMPOULES","AMPULLAIRE","AMPULLAIRES","ANABAS","ANABLEPS","ANACONDA","ANACONDAS","ANATIDE","ANATIDES","ANATIFE",
    "ANATIFES","ANCHOIS","ANDALOU","ANDALOUS","ANE","ANES","ANESSE","ANESSES","ANGE","ANGES","ANGORA","ANGORAS","ANGUILLE","ANGUILLES","ANHINGA",
    "ANHINGAS","ANKYLOSAURE","ANKYLOSAURES","ANODONTE","ANODONTES","ANOLI","ANOLIS","ANOMALURE","ANOMALURES","ANOMOURE","ANOMOURES","ANON",
    "ANONS","ANOURE","ANOURES","ANSERIFORME","ANSERIFORMES","ANTILOPE","ANTILOPES","APATOSAURE","APATOSAURES","APHRODITE","APHRODITES","APOTRE",
    "APOTRES","APTERYX","ARA","ARABE","ARABES","ARAIGNEE","ARAIGNEES","ARAPEDE","ARAPEDES","ARAS","ARCHEOPTERYX","ARCHITEUTHIS","ARDENNAIS",
    "ARENICOLE","ARENICOLES","ARGIOPE","ARGIOPES","ARGONAUTE","ARGONAUTES","ARGUS","ARGYRONETE","ARGYRONETES","ARIEGEOIS","ARLEQUIN","ARLEQUINS",
    "ARONDE","ARONDES","ARTEMIA","ARTEMIAS","ARZEL","ARZELS","ASCARIDE","ASCARIDES","ASCARIS","ASCIDIE","ASCIDIES","ASELLE","ASELLES","ASIATIQUE",
    "ASIATIQUES","ASPE","ASPES","ASPIC","ASPICS","ASTARTE","ASTARTES","ASTERIDE","ASTERIDES","ASTERIE","ASTERIES","ASTRILD","ASTRILDS","ATELE",
    "ATELES","ATIPA","ATIPAS","ATLANTOSAURE","ATLANTOSAURES","AUBERE","AUBERES","AUBRAC","AUBRACS","AURELIE","AURELIES","AUROCHS","AUTOUR",
    "AUTOURS","AUTRUCHE","AUTRUCHES","AUTRUCHON","AUTRUCHONS","AVELINE","AVELINES","AVICULE","AVICULES","AVOCETTE","AVOCETTES","AXIS","AXOLOTL",
    "AXOLOTLS","AZTEQUE","AZTEQUES","BABILLARD","BABILLARDS","BABIROUSSA","BABIROUSSAS","BABOUIN","BABOUINS","BADECHE","BADECHES","BALANE",
    "BALANES","BALAOU","BALAOUS","BALBUZARD","BALBUZARDS","BALEINE","BALEINEAU","BALEINEAUX","BALEINES","BALEINOPTERE","BALEINOPTERES",
    "BALENOPTERE","BALENOPTERES","BALINAIS","BALISTE","BALISTES","BANDICOOT","BANDICOOTS","BAR","BARBE","BARBEAU","BARBEAUX","BARBES","BARBET",
    "BARBETS","BARBIER","BARBIERS","BARBOT","BARBOTE","BARBOTES","BARBOTS","BARBOTTE","BARBOTTES","BARBU","BARBUE","BARBUES","BARBUS","BARDEAU",
    "BARDEAUX","BARDOT","BARDOTS","BARGE","BARGES","BARIBAL","BARIBALS","BARNACHE","BARNACHES","BARNACLE","BARNACLES","BARRACUDA","BARRACUDAS",
    "BARS","BARTAVELLE","BARTAVELLES","BARZOI","BARZOIS","BASILIC","BASILICS","BASSET","BASSETS","BATELEUR","BATELEURS","BAUD","BAUDET","BAUDETS",
    "BAUDROIE","BAUDROIES","BAUDS","BAZADAIS","BAZADAISE","BAZADAISES","BEAGLE","BEAGLES","BEAUCERON","BEAUCERONS","BECARD","BECARDS","BECASSE",
    "BECASSEAU","BECASSEAUX","BECASSES","BECASSINE","BECASSINES","BECCARD","BECCARDS","BECFIGUE","BECFIGUES","BELETTE","BELETTES","BELIER","BELIERS",
    "BELON","BELONS","BELOUGA","BELOUGAS","BELUGA","BELUGAS","BENGALI","BENGALIS","BENITIER","BENITIERS","BERGER","BERGERE","BERGERES","BERGERETTE",
    "BERGERETTES","BERGERONNETTE","BERGERONNETTES","BERGERS","BERNACHE","BERNACHES","BERNACLE","BERNACLES","BERNICLE","BERNICLES","BERNIQUE",
    "BERNIQUES","BERYX","BICHE","BICHES","BICHIQUE","BICHIQUES","BICHON","BICHONNE","BICHONNES","BICHONS","BICOT","BICOTS","BIDET","BIDETS","BIEVRE",
    "BIEVRES","BIGHORN","BIGHORNS","BIGLE","BIGLES","BIGORNEAU","BIGORNEAUX","BIHOREAU","BIHOREAUX","BIQUET","BIQUETS","BIQUETTE","BIQUETTES","BIRMAN",
    "BIRMANS","BISET","BISETS","BISETTE","BISETTES","BISON","BISONNE","BISONNES","BISONS","BIZET","BIZETS","BLAIREAU","BLAIREAUX","BLANCHET",
    "BLANCHETS","BLANCHON","BLANCHONS","BLENNIE","BLENNIES","BLEU","BLEUS","BLUETTE","BLUETTES","BOA","BOAS","BOBTAIL","BOBTAILS","BOER","BOERS",
    "BOEUF","BOEUFS","BOMBYX","BONDELLE","BONDELLES","BONDREE","BONDREES","BONELLIE","BONELLIES","BONGARE","BONGARES","BONGO","BONGOS","BONITE",
    "BONITES","BONOBO","BONOBOS","BOSNIEN","BOSNIENS","BOUC","BOUCAUD","BOUCAUDS","BOUCOT","BOUCOTS","BOUCS","BOULEDOGUE","BOULEDOGUES","BOULONNAIS",
    "BOUQUETIN","BOUQUETINS","BOURGEOIS","BOURRICOT","BOURRICOTS","BOURRIN","BOURRINS","BOUVIER","BOUVIERE","BOUVIERES","BOUVIERS","BOUVILLON",
    "BOUVILLONS","BOUVREUIL","BOUVREUILS","BOXER","BOXERS","BRACHIOSAURE","BRACHIOSAURES","BRACHYOURE","BRACHYOURES","BRADYPE","BRADYPES","BRANCHIOPODE",
    "BRANCHIOPODES","BRANTE","BRANTES","BRAQUE","BRAQUES","BREBIS","BREME","BREMES","BRETON","BRETONS","BREVE","BREVES","BRIARD","BRIARDS","BRIQUET",
    "BRIQUETS","BROCARD","BROCARDS","BROCHET","BROCHETON","BROCHETONS","BROCHETS","BRONTOSAURE","BRONTOSAURES","BROQUARD","BROQUARDS","BROQUART",
    "BROQUARTS","BRUANT","BRUANTS","BUBALE","BUBALES","BUCCIN","BUCCINS","BUFFLE","BUFFLES","BUFFLESSE","BUFFLESSES","BUFFLON","BUFFLONNE","BUFFLONNES",
    "BUFFLONS","BULBUL","BULBULS","BULL","BULLDOG","BULLDOGS","BULLS","BULOT","BULOTS","BURMESE","BURMESES","BUSAIGLE","BUSAIGLES","BUSARD",
    "BUSARDS","BUSE","BUSES","BUTOR","BUTORS","CABARET","CABARETS","CABIAI","CABIAIS","CABILLAU","CABILLAUD","CABILLAUDS","CABILLAUX","CABOT","CABOTS",
    "CABRI","CABRIS","CACAOUI","CACAOUIS","CACATOES","CACHALOT","CACHALOTS","CACIQUE","CACIQUES","CAGOU","CAGOUILLE","CAGOUILLES","CAGOUS","CAILLE",
    "CAILLES","CAILLETEAU","CAILLETEAUX","CAILLETTE","CAILLETTES","CAIMAN","CAIMANS","CAIQUE","CAIQUES","CALABRAIS","CALAMAR","CALAMARS","CALAMITE",
    "CALAMITES","CALANDRE","CALANDRES","CALAO","CALAOS","CALFAT","CALFATS","CALMAR","CALMARS","CAMELEON","CAMELEONS","CAMPAGNOL","CAMPAGNOLS",
    "CANADIEN","CANADIENS","CANARD","CANARDEAU","CANARDEAUX","CANARDS","CANARI","CANARIS","CANCALE","CANCALES","CANCRE","CANCRES","CANE","CANEPETIERE",
    "CANEPETIERES","CANES","CANETON","CANETONS","CANETTE","CANETTES","CANICHE","CANICHES","CANICHON","CANICHONS","CAOUANE","CAOUANES","CAOUANNE",
    "CAOUANNES","CAPELAN","CAPELANS","CAPITAINE","CAPITAINES","CAPRIMULGIFORME","CAPUCIN","CAPUCINS","CAPYBARA","CAPYBARAS","CARACAL","CARACALS",
    "CARACUL","CARACULS","CARANGUE","CARANGUES","CARASSIN","CARASSINS","CARCAJOU","CARCAJOUS","CARDINAL","CARDINAUX","CARET","CARETS","CARIACOU",
    "CARIACOUS","CARIBOU","CARIBOUS","CARICOLE","CARICOLES","CARLIN","CARLINS","CARME","CARMES","CAROUGE","CAROUGES","CARPE","CARPEAU","CARPEAUX",
    "CARPES","CARPILLON","CARPILLONS","CARRELET","CARRELETS","CASOAR","CASOARS","CASQUE","CASQUES","CASTOR","CASTORS","CAURI","CAURIS","CAVALE",
    "CAVALES","CEBIDE","CEBIDES","CECILIE","CECILIES","CENURE","CENURES","CERASTE","CERASTES","CERCOPITHEQUE","CERCOPITHEQUES","CERF","CERFS","CERITE",
    "CERITES","CERITHE","CERITHES","CETEAU","CETEAUX","CHABOT","CHABOTS","CHACAL","CHACALS","CHAENICHTHYS","CHAENICHTYS","CHAMEAU","CHAMEAUX","CHAMELLE",
    "CHAMELLES","CHAMELON","CHAMELONS","CHAMOIS","CHAPON","CHAPONNEAU","CHAPONNEAUX","CHAPONS","CHARADRIIDE","CHARADRIIDES","CHARDONNERET","CHARDONNERETS",
    "CHAROLAISE","CHAROLAISES","CHARTREUX","CHAT","CHATON","CHATONS","CHATOU","CHATOUILLE","CHATOUILLES","CHATOUS","CHATROU","CHATROUS","CHATS",
    "CHATTE","CHATTES","CHEVAINE","CHEVAINES","CHEVAL","CHEVALIER","CHEVALIERS","CHEVAUX","CHEVECHE","CHEVECHES","CHEVENNE","CHEVENNES","CHEVESNE",
    "CHEVESNES","CHEVRE","CHEVREAU","CHEVREAUX","CHEVRES","CHEVRETTE","CHEVRETTES","CHEVREUIL","CHEVREUILS","CHEVRILLARD","CHEVRILLARDS","CHEVROTAIN",
    "CHEVROTAINS","CHIEN","CHIENNE","CHIENNES","CHIENS","CHIHUAHUA","CHIHUAHUAS","CHIMERE","CHIMERES","CHIMPANZE","CHIMPANZES","CHINCHARD","CHINCHARDS",
    "CHINCHILLA","CHINCHILLAS","CHINOIS","CHIONIS","CHIOT","CHIOTS","CHIPIRON","CHIPIRONS","CHIPMUNK","CHIPMUNKS","CHIRURGIEN","CHIRURGIENS","CHITON",
    "CHITONS","CHOCARD","CHOCARDS","CHOUCAS","CHOUETTE","CHOUETTES","CIGOGNE","CIGOGNEAU","CIGOGNEAUX","CIGOGNES","CINCLE","CINCLES","CIRCAETE",
    "CIRCAETES","CIRON","CIRONS","CISTICOLE","CISTICOLES","CISTUDE","CISTUDES","CIVELLE","CIVELLES","CIVETTE","CIVETTES","CLABAUD","CLABAUDS","CLAM",
    "CLAMS","CLARIAS","CLAVAIRE","CLAVAIRES","CLOPORTE","CLOPORTES","CLOVISSE","CLOVISSES","COATI","COATIS","COB","COBAYE","COBAYES","COBRA","COBRAS",
    "COBS","COCHE","COCHELET","COCHELETS","COCHES","COCHET","COCHETS","COCHETTE","COCHETTES","COCHEVIS","COCHON","COCHONNET","COCHONNETS","COCHONS",
    "COCKER","COCKERS","COELACANTHE","COELACANTHES","COENURE","COENURES","COFFRE","COFFRES","COITRON","COITRONS","COLIBRI","COLIBRIS","COLIMACON",
    "COLIMACONS","COLIN","COLINEAU","COLINEAUX","COLINOT","COLINOTS","COLINS","COLLEY","COLLEYS","COLOBE","COLOBES","COLOMBE","COLOMBES","COLOMBINE",
    "COLOMBINES","COLVERT","COLVERTS","COMATULE","COMATULES","COMBASSOU","COMBASSOUS","COMBATTANT","COMBATTANTS","COMTOIS","CONDOR","CONDORS","CONE",
    "CONES","CONGRE","CONGRES","CONQUE","CONQUES","CONSTRICTEUR","CONSTRICTEURS","CONSTRICTOR","CONSTRICTORS","COQ","COQS","COQUATRE","COQUATRES",
    "COQUE","COQUELET","COQUELETS","COQUES","COQUETTE","COQUETTES","CORAIL","CORAUX","CORBEAU","CORBEAUX","CORBILLAT","CORBILLATS","CORBIN","CORBINS",
    "CORDONNIER","CORDONNIERS","COREGONE","COREGONES","CORMORAN","CORMORANS","CORNEILLARD","CORNEILLARDS","CORNEILLE","CORNEILLES","CORNEILLON",
    "CORNEILLONS","CORNIAUD","CORNIAUDS","CORNIOT","CORNIOTS","CORONELLE","CORONELLES","CORYPHENE","CORYPHENES","COTINGA","COTINGAS","COTTE","COTTES",
    "COUAGGA","COUAGGAS","COUCOU","COUCOUS","COUDOU","COUDOUS","COUGOUAR","COUGOUARS","COUGUAR","COUGUARS","COULEUVRE","COULEUVRES","COULON","COULONS",
    "COURLAN","COURLANS","COURLIEU","COURLIEUX","COURLIS","COUROUCOU","COUROUCOUS","COUSCOUS","COUTEAU","COUTEAUX","COUTURIERE","COUTURIERES","COYOTE",
    "COYOTES","CRABE","CRABES","CRABIER","CRABIERS","CRADOT","CRADOTS","CRAPAUD","CRAPAUDINE","CRAPAUDINES","CRAPAUDS","CRAPET","CRAPETS","CRAPETTE",
    "CRAPETTES","CRAVATE","CRAVATES","CRAVE","CRAVES","CREA","CREAS","CRECERELLE","CRECERELLES","CREPIDULE","CREPIDULES","CRETOIS","CREVETTE","CREVETTES",
    "CROCODILE","CROCODILES","CROSSOPTERYGIEN","CROTALE","CROTALES","CUBOMEDUSE","CUBOMEDUSES","CUILLER","CUILLERS","CYCLOPE","CYCLOPES","CYCLOPTERE",
    "CYCLOPTERES","CYCLOSTOME","CYCLOSTOMES","CYGNE","CYGNES","CYNOCEPHALE","CYNOCEPHALES","CYNOGLOSSE","CYNOGLOSSES","CYON","CYONS","CYPRIN","CYPRINS",
    "CYPRIS","DACTYLOPTERE","DACTYLOPTERES","DAGUET","DAGUETS","DAHU","DAHUS","DAIM","DAIMS","DAINE","DAINES","DALMATIEN","DALMATIENS","DAMA","DAMALISQUE",
    "DAMALISQUES","DAMAN","DAMANS","DAMAS","DAMIER","DAMIERS","DANIO","DANIOS","DANOIS","DANUBIEN","DANUBIENS","DAPHNIE","DAPHNIES","DARBON",
    "DARBONS","DARD","DARDS","DASYURE","DASYURES","DAUPHIN","DAUPHINS","DAURADE","DAURADES","DAUW","DAUWS","DAW","DAWS","DECAPODE","DECAPODES",
    "DEMOISELLE","DEMOISELLES","DENDROBATE","DENDROBATES","DENDROLAGUE","DENDROLAGUES","DENTALE","DENTALES","DENTE","DENTES","DENTIROSTRE","DENTIROSTRES",
    "DESMAN","DESMANS","DESTRIER","DESTRIERS","DHOLE","DHOLES","DIAMANT","DIAMANTS","DIANE","DIANES","DINDE","DINDES","DINDON","DINDONNE","DINDONNEAU",
    "DINDONNEAUX","DINDONNES","DINDONS","DINGO","DINGOS","DIODON","DIODONS","DISCUS","DOBERMAN","DOBERMANS","DODO","DODOS","DOGUE","DOGUES","DOGUIN",
    "DOGUINE","DOGUINES","DOGUINS","DON","DONAX","DONS","DONZELLE","DONZELLES","DORADE","DORADES","DOREE","DOREES","DORIS","DOUVE","DOUVES","DRAGON",
    "DRAGONS","DRAINE","DRAINES","DRENNE","DRENNES","DREPANORNIS","DRILL","DRILLS","DROMADAIRE","DROMADAIRES","DROME","DROMES","DRONTE","DRONTES",
    "DUC","DUCHESSE","DUCHESSES","DUCS","DUGON","DUGONG","DUGONGS","DUGONS","DURHAM","DURHAMS","DYNASTE","DYNASTES","ECHASSE","ECHASSES","ECHASSIER",
    "ECHASSIERS","ECHELETTE","ECHELETTES","ECHENILLEUR","ECHENILLEURS","ECHIDNE","ECHIDNES","ECHINIDE","ECHINIDES","ECREVISSE","ECREVISSES",
    "ECTOPROCTE","ECTOPROCTES","ECUREUIL","ECUREUILS","EFFARVATE","EFFARVATES","EFFARVATTE","EFFARVATTES","EFFRAIE","EFFRAIES","EGLEFIN","EGLEFINS",
    "EIDER","EIDERS","ELAN","ELAND","ELANDS","ELANS","ELAPHE","ELAPHES","ELBOT","ELBOTS","ELEPHANT","ELEPHANTE","ELEPHANTEAU","ELEPHANTEAUX",
    "ELEPHANTES","ELEPHANTS","ELIS","EMERAUDE","EMERAUDES","EMERILLON","EMERILLONS","EMEU","EMEUS","EMISSOLE","EMISSOLES","EMOU","EMOUCHET","EMOUCHETS",
    "EMOUS","EMPEREUR","EMPEREURS","EMYDE","EMYDES","ENCORNET","ENCORNETS","ENCRINE","ENCRINES","ENDORMI","ENDORMIS","ENGOULEVENT","ENGOULEVENTS",
    "ENTELLE","ENTELLES","EOHIPPUS","EPAGNEUL","EPAGNEULE","EPAGNEULES","EPAGNEULS","EPAULARD","EPAULARDS","EPEICHE","EPEICHES","EPEIRE","EPEIRES",
    "EPERLAN","EPERLANS","EPERVIER","EPERVIERE","EPERVIERES","EPERVIERS","EPINOCHE","EPINOCHES","EPONGE","EPONGES","EQUILLE","EQUILLES","ERMITE",
    "ERMITES","ESCARGOT","ESCARGOTS","ESCLAVE","ESCLAVES","ESPADON","ESPADONS","ESQUIMAU","ESQUIMAUX","ESTURGEON","ESTURGEONS","ETALON","ETALONS",
    "ETOURNEAU","ETOURNEAUX","ETRILLE","ETRILLES","EUNECTE","EUNECTES","EUROPEEN","EUROPEENS","EVEQUE","EVEQUES","EXOCET","EXOCETS","EXOTIQUE",
    "EXOTIQUES","EYRA","EYRAS","FAISAN","FAISANDEAU","FAISANDEAUX","FAISANE","FAISANES","FAISANS","FAON","FAONS","FARIO","FARIOS","FARLOUSE",
    "FARLOUSES","FAUCHEUX","FAUCON","FAUCONNEAU","FAUCONNEAUX","FAUCONS","FAUVETTE","FAUVETTES","FEMME","FEMMES","FENNEC","FENNECS","FERA","FERAS",
    "FJORD","FJORDS","FLAMANT","FLAMANTS","FLET","FLETAN","FLETANS","FLETS","FOSSA","FOSSANE","FOSSANES","FOSSAS","FOU","FOUINE","FOUINES",
    "FOULQUE","FOULQUES","FOURMILIER","FOURMILIERS","FOURNIER","FOURNIERS","FOUS","FOX","FRANCOLIN","FRANCOLINS","FREGATE","FREGATES","FREUX",
    "FRIQUET","FRIQUETS","FRISON","FRISONNE","FRISONNES","FRISONS","FULIGULE","FULIGULES","FULMAR","FULMARS","FURET","FURETS","FURIE","FURIES",
    "FURIOSO","FURIOSOS","GALAGO","GALAGOS","GALATHEE","GALATHEES","GALEODE","GALEODES","GALIBOT","GALIBOTS","GALIDIA","GALIDIAS","GALIDIE","GALIDIES",
    "GALLINULE","GALLINULES","GAMBA","GAMBAS","GAMBETTE","GAMBETTES","GAMBUSIE","GAMBUSIES","GAMMARE","GAMMARES","GANGA","GANGAS","GARDON",
    "GARDONS","GARENNE","GARENNES","GARROT","GARROTS","GARZETTE","GARZETTES","GAUR","GAURS","GAVIAL","GAVIALS","GAYAL","GAYALS","GAZELLE","GAZELLES",
    "GEAI","GEAIS","GECKO","GECKOS","GELINE","GELINES","GELINOTTE","GELINOTTES","GENET","GENETS","GENETTE","GENETTES","GENISSE","GENISSES",
    "GERBILLE","GERBILLES","GERBOISE","GERBOISES","GERFAUT","GERFAUTS","GERMON","GERMONS","GERRIS","GIBBON","GIBBONS","GIRAFE","GIRAFEAU",
    "GIRAFEAUX","GIRAFES","GIRAFON","GIRAFONS","GIRELLE","GIRELLES","GLADIATEUR","GLADIATEURS","GLAIVE","GLAIVES","GLAREOLE","GLAREOLES",
    "GLOBICEPHALE","GLOBICEPHALES","GLOUTON","GLOUTONS","GLYPTODON","GLYPTODONS","GLYPTODONTE","GLYPTODONTES","GNOU","GNOUS","GOBEMOUCHE",
    "GOBEMOUCHES","GOBERGE","GOBERGES","GOBIE","GOBIES","GODE","GODES","GOELAND","GOELANDS","GOGLU","GOGLUS","GOLIATH","GOLIATHS","GONELLE",
    "GONELLES","GONNELLE","GONNELLES","GORET","GORETS","GORFOU","GORFOUS","GORGONE","GORGONES","GORILLE","GORILLES","GOUJON","GOUJONS","GOULU",
    "GOULUS","GOUPIL","GOUPILS","GOURA","GOURAMI","GOURAMIS","GOURAS","GRAVELOT","GRAVELOTS","GREBE","GREBES","GREFFIER","GREFFIERS","GREMILLE",
    "GREMILLES","GRENADIER","GRENADIERS","GRENADIN","GRENADINS","GRENAT","GRENATS","GRENOUILLE","GRENOUILLES","GREYHOUND","GREYHOUNDS","GRIFFON",
    "GRIFFONS","GRIMAUD","GRIMAUDS","GRIMPEREAU","GRIMPEREAUX","GRISARD","GRISARDS","GRISET","GRISETS","GRISON","GRISONS","GRIVE","GRIVES","GRIVET",
    "GRIVETS","GRIZZLI","GRIZZLIS","GRIZZLY","GRIZZLYS","GROENENDAEL","GROENENDAELS","GROGNEUR","GROGNEURS","GROLE","GROLES","GRONDIN","GRONDINS",
    "GROUSE","GROUSES","GRUAU","GRUAUX","GRUE","GRUES","GRUON","GRUONS","GRYPHEE","GRYPHEES","GUANACO","GUANACOS","GUENON","GUENONS","GUEPARD",
    "GUEPARDS","GUEPIER","GUEPIERS","GUEREZA","GUEREZAS","GUIB","GUIBS","GUIFETTE","GUIFETTES","GUILLEMOT","GUILLEMOTS","GUPPIES","GUPPY",
    "GUPPYS","GYMNOTE","GYMNOTES","GYPAETE","GYPAETES","HAJE","HAJES","HALBRAN","HALBRANS","HALIOTIS","HAMADRYAS","HAMSTER","HAMSTERS",
    "HANOVRIEN","HANOVRIENS","HAPALIDE","HAPALIDES","HAQUENEE","HAQUENEES","HARENG","HARENGS","HARENGUET","HARENGUETS","HARET","HARETS",
    "HARFANG","HARFANGS","HARIDELLE","HARIDELLES","HARLE","HARLES","HARPE","HARPES","HARPIE","HARPIES","HARRIER","HARRIERS","HASE","HASES",
    "HATTERIA","HATTERIAS","HEMIONE","HEMIONES","HERE","HERES","HERISSON","HERISSONNE","HERISSONNES","HERISSONS","HERMINE","HERMINES",
    "HERON","HERONNEAU","HERONNEAUX","HERONS","HIBOU","HIBOUX","HIMALAYEN","HIMALAYENS","HIPPOCAMPE","HIPPOCAMPES","HIPPOPOTAME","HIPPOPOTAMES",
    "HIRONDEAU","HIRONDEAUX","HIRONDELLE","HIRONDELLES","HOAZIN","HOAZINS","HOCCO","HOCCOS","HOLLANDAIS","HOLSTEIN","HOLSTEINS","HOMARD",
    "HOMARDS","HOMME","HOMMES","HONGRE","HONGRES","HOTU","HOTUS","HUARD","HUARDS","HUART","HUARTS","HUITRE","HUITRES","HUITRIER","HUITRIERS",
    "HULOTTE","HULOTTES","HUNTER","HUNTERS","HUPPE","HUPPES","HURLEUR","HURLEURS","HUSKIES","HUSKY","HUSKYS","HYDRE","HYDRES","HYENE","HYENES",
    "IBIS","ICHTYORNIS","ICHTYOSAURE","ICHTYOSAURES","ICHTYOSTEGA","ICHTYOSTEGAS","IDE","IDES","IGNICOLE","IGNICOLES","IGUANE","IGUANES",
    "IGUANODON","IGUANODONS","IMPALA","IMPALAS","INDICATEUR","INDICATEURS","INDRI","INDRICOTHERIUM","INDRICOTHERIUMS","INDRIS","INSEPARABLE",
    "INSEPARABLES","ISABELLE","ISABELLES","ISARD","ISARDS","ISATIS","ISLANDAIS","ISOCARDE","ISOCARDES","IULE","IULES","JABIRU","JABIRUS","JACAMAR",
    "JACAMARS","JACANA","JACANAS","JACO","JACOS","JACQUET","JACQUETS","JAGUAR","JAGUARONDI","JAGUARONDIS","JAGUARS","JANTHINE","JANTHINES","JAQUET",
    "JAQUETS","JARRET","JARRETS","JARS","JASEUR","JASEURS","JAVA","JAVANAIS","JAVAS","JOCASSE","JOCASSES","JOSEPH","JOSEPHS","JUBARTE","JUBARTES",
    "JUDELLE","JUDELLES","JULIENNE","JULIENNES","JUMENT","JUMENTS","JUNCO","JUNCOS","KAKATOES","KAKAWI","KAKAWIS","KAMICHI","KAMICHIS","KAMPTOZOAIRE",
    "KAMPTOZOAIRES","KANGOUROU","KANGOUROUS","KARAKUL","KARAKULS","KARBAU","KARBAUS","KARBAUX","KEA","KEAS","KENYAPITHEQUE","KENYAPITHEQUES",
    "KERABAU","KERABAUS","KERABAUX","KIKIWI","KIKIWIS","KINKAJOU","KINKAJOUS","KIWI","KIWIS","KOALA","KOALAS","KOB","KOBS","KODIAK","KODIAKS",
    "KOOKABURRA","KOOKABURRAS","KORTHALS","KOUDOU","KOUDOUS","KOUPREY","KOUPREYS","KRILL","KRILLS","LABBE","LABBES","LABRADOR","LABRADORS",
    "LABRE","LABRES","LABRI","LABRIS","LABRIT","LABRITS","LACAUNE","LACAUNES","LAGOPEDE","LAGOPEDES","LAGOTHRIX","LAGOTRICHE","LAGOTRICHES",
    "LAIE","LAIES","LAIMARGUE","LAIMARGUES","LAMA","LAMANTIN","LAMANTINS","LAMAS","LAMBI","LAMBIS","LAMIE","LAMIES","LAMPROIE","LAMPROIES",
    "LAMPYRE","LAMPYRES","LANCON","LANCONS","LANDRACE","LANDRACES","LANERET","LANERETS","LANGOUSTE","LANGOUSTES","LANGOUSTINE","LANGOUSTINES",
    "LANGUR","LANGURS","LANICE","LANICES","LANIER","LANIERS","LAPEREAU","LAPEREAUX","LAPIN","LAPINE","LAPINES","LAPINS","LARVE","LARVES",
    "LATRODECTE","LATRODECTES","LAVARET","LAVARETS","LAVIGNON","LAVIGNONS","LEGHORN","LEGHORNS","LEIPOA","LEIPOAS","LEMMING","LEMMINGS",
    "LEMUR","LEMURE","LEMURES","LEMURS","LEONBERG","LEONBERGS","LEOPARD","LEOPARDE","LEOPARDES","LEOPARDS","LEPIDOSIREN","LEPIDOSIRENE",
    "LEPIDOSIRENES","LEPIDOSIRENS","LEPIDOSTEE","LEPIDOSTEES","LEPISOSTEE","LEPISOSTEES","LEROT","LEROTS","LETTON","LETTONS","LEU","LEVRAUT",
    "LEVRAUTS","LEVRETTE","LEVRETTES","LEVRIER","LEVRIERS","LEVRON","LEVRONNE","LEVRONNES","LEVRONS","LEZARD","LEZARDE","LEZARDES","LEZARDS",
    "LIARD","LIARDS","LICE","LICES","LICHE","LICHES","LIEU","LIEUS","LIEVRE","LIEVRES","LIGIE","LIGIES","LIMACE","LIMACES","LIMACON",
    "LIMACONS","LIMANDE","LIMANDES","LIME","LIMES","LIMIER","LIMIERS","LIMNEE","LIMNEES","LIMULE","LIMULES","LINGUE","LINGUES","LINOTTE",
    "LINOTTES","LINSANG","LINSANGS","LION","LIONCEAU","LIONCEAUX","LIONNE","LIONNES","LIONS","LIPARIS","LIPIZZAN","LIPIZZANS","LIRON","LIRONS",
    "LISETTE","LISETTES","LITHODOME","LITHODOMES","LITORNE","LITORNES","LITTORINE","LITTORINES","LOCHE","LOCHES","LOCUSTELLE","LOCUSTELLES",
    "LOIR","LOIRS","LOMBRIC","LOMBRICS","LOMPE","LOMPES","LOPHOPHORE","LOPHOPHORES","LOQUETTE","LOQUETTES","LORETTE","LORETTES","LORI",
    "LORICAIRE","LORICAIRES","LORIOT","LORIOTS","LORIQUET","LORIQUETS","LORIS","LOTE","LOTES","LOTTE","LOTTES","LOULOU","LOULOUS","LOUP",
    "LOUPS","LOUTRE","LOUTRES","LOUVE","LOUVES","LOUVETEAU","LOUVETEAUX","LUCERNAIRE","LUCERNAIRES","LUISETTE","LUISETTES","LULU","LULUS","LUMA",
    "LUMAS","LUMP","LUMPS","LUNE","LUNES","LUSITANIEN","LUSITANIENS","LUTH","LUTHS","LUTRAIRE","LUTRAIRES","LYCAON","LYCAONS","LYCOSE","LYCOSES",
    "LYNX","MAATJE","MAATJES","MACAQUE","MACAQUES","MACAREUX","MACHAON","MACHAONS","MACREUSE","MACREUSES","MACROCHEIRE","MACROCHEIRES",
    "MACROSCELIDE","MACROSCELIDES","MACROURE","MACROURES","MACTRE","MACTRES","MADREPORE","MADREPORES","MAGNAN","MAGNANS","MAGOT","MAGOTS",
    "MAIA","MAIAS","MAIGRE","MAIGRES","MAILLET","MAILLETS","MAINATE","MAINATES","MAKAIRE","MAKAIRES","MAKI","MAKIS","MALAMUTE","MALAMUTES",
    "MALARD","MALARDS","MALART","MALARTS","MALINOIS","MALINOISE","MALINOISES","MALMIGNATTE","MALMIGNATTES","MALPEQUE","MALPEQUES","MALURE",
    "MALURES","MAMBA","MAMBAS","MAMMOUTH","MAMMOUTHS","MANCHOT","MANCHOTS","MANDARIN","MANDARINS","MANDRILL","MANDRILLS","MANGABEY","MANGABEYS",
    "MANGOUSTE","MANGOUSTES","MANGUE","MANGUES","MANTA","MANTAS","MANTE","MANTES","MANX","MAQUEREAU","MAQUEREAUX","MARA","MARABOUT","MARABOUTS",
    "MARANS","MARAS","MARBRE","MARBRES","MARCASSIN","MARCASSINS","MARENNES","MARGAY","MARGAYS","MARGOUILLAT","MARGOUILLATS","MARLIN","MARLINS",
    "MARMOTTE","MARMOTTES","MAROUETTE","MAROUETTES","MARSOUIN","MARSOUINS","MARTE","MARTEAU","MARTEAUX","MARTES","MARTIN","MARTINET","MARTINETS",
    "MARTINS","MARTRE","MARTRES","MASAI","MASAIS","MASKINONGE","MASKINONGES","MASTIFF","MASTIFFS","MATAMATA","MATAMATAS","MATIN","MATINS",
    "MATOU","MATOUS","MAUBECHE","MAUBECHES","MAUVIETTE","MAUVIETTES","MAUVIS","MAZAMA","MAZAMAS","MEDUSE","MEDUSES","MEGACEROS","MEGALOSAURE",
    "MEGALOSAURES","MEGAPODE","MEGAPODES","MEGAPTERE","MEGAPTERES","MEGATHERIUM","MEGATHERIUMS","MEHARA","MEHARI","MEHARIS","MELEAGRINE",
    "MELEAGRINES","MENDOLE","MENDOLES","MENON","MENONS","MENOPOME","MENOPOMES","MENURE","MENURES","MERENS","MERGULE","MERGULES","MERINOS",
    "MERLAN","MERLANS","MERLE","MERLEAU","MERLEAUX","MERLES","MERLETTE","MERLETTES","MERLIN","MERLINS","MERLU","MERLUCHE","MERLUCHES",
    "MERLUS","MEROU","MEROUS","MESANGE","MESANGEAI","MESANGEAIS","MESANGES","MESSAGER","MESSAGERS","MEUNIERE","MEUNIERES","MICROCHIROPTERE",
    "MIGRAINE","MIGRAINES","MILAN","MILANDRE","MILANDRES","MILANEAU","MILANEAUX","MILANS","MILOUIN","MILOUINS","MINISTRE","MINISTRES",
    "MINON","MINONS","MINORQUIN","MINORQUINS","MISTIGRI","MISTIGRIS","MOA","MOAS","MOCASSIN","MOCASSINS","MOFETTE","MOFETTES","MOINE","MOINEAU",
    "MOINEAUX","MOINES","MOLE","MOLES","MOLLE","MOLLES","MOLLUSQUE","MOLLUSQUES","MOLOCH","MOLOCHS","MOLOSSE","MOLOSSES","MOLURE","MOLURES",
    "MONDAIN","MONDAINS","MONTBELIARD","MONTBELIARDS","MONTICOLE","MONTICOLES","MOQUEUR","MOQUEURS","MORILLON","MORILLONS","MORSE","MORSES",
    "MORUE","MORUES","MOSTELLE","MOSTELLES","MOTELLE","MOTELLES","MOTTEUX","MOUCHEROLLE","MOUCHEROLLES","MOUCHET","MOUCHETS","MOUETTE",
    "MOUETTES","MOUFETTE","MOUFETTES","MOUFFETTE","MOUFFETTES","MOUFLON","MOUFLONS","MOULE","MOULES","MOUSTAC","MOUSTACS","MOUTON","MOUTONS",
    "MUGE","MUGES","MULARD","MULARDE","MULARDES","MULARDS","MULASSE","MULASSES","MULE","MULES","MULET","MULETS","MULETTE","MULETTES","MULOT",
    "MULOTS","MUNTJAC","MUNTJACS","MURENE","MURENES","MUREX","MURIN","MURINS","MURMEL","MURMELS","MUSARAIGNE","MUSARAIGNES","MUSCARDIN",
    "MUSCARDINS","MUSETTE","MUSETTES","MUSTANG","MUSTANGS","MYE","MYES","MYGALE","MYGALES","MYOPOTAME","MYOPOTAMES","MYRMIDON","MYRMIDONS",
    "MYXINE","MYXINES","NAJA","NAJAS","NANDINIE","NANDINIES","NANDOU","NANDOUS","NAPOLEON","NAPOLEONS","NARVAL","NARVALS","NASIQUE","NASIQUES",
    "NATICE","NATICES","NAUTILE","NAUTILES","NDAMA","NDAMAS","NEBULEUSE","NEBULEUSES","NEMERTE","NEMERTES","NEON","NEONS","NEOPILINA","NEOPILINAS",
    "NEREIDE","NEREIDES","NEREIS","NERITE","NERITES","NETTE","NETTES","NILGAUT","NILGAUTS","NIVEROLLE","NIVEROLLES","NOCTUELLE","NOCTUELLES",
    "NOCTULE","NOCTULES","NONNETTE","NONNETTES","NORVEGIEN","NORVEGIENS","NOURRAIN","NOURRAINS","NOVILLO","NOVILLOS","NUDIBRANCHE","NUDIBRANCHES",
    "NYCTALE","NYCTALES","OBLADE","OBLADES","OCELOT","OCELOTS","OEDICNEME","OEDICNEMES","OIE","OIES","OISEAU","OISEAUX","OISELET","OISELETS",
    "OISILLON","OISILLONS","OISON","OISONS","OKAPI","OKAPIS","OLIGOCHETE","OLIGOCHETES","OMBLE","OMBLES","OMBRE","OMBRES","OMBRETTE","OMBRETTES",
    "OMBRINE","OMBRINES","ONAGRE","ONAGRES","ONCE","ONCES","ONDATRA","ONDATRAS","ONYCHOPHORE","ONYCHOPHORES","OPHIDIEN","OPHIDIENS","OPHIURE",
    "OPHIURES","OPHIURIDE","OPHIURIDES","OPILION","OPILIONS","OPISTHOBRANCHE","OPISTHOBRANCHES","OPOSSUM","OPOSSUMS","OREILLARD","OREILLARDS",
    "OREOPITHEQUE","OREOPITHEQUES","ORFRAIE","ORFRAIES","ORIENTAL","ORIENTAUX","ORIGNAL","ORIGNAUX","ORIOLE","ORIOLES","ORMEAU","ORMEAUX",
    "ORMET","ORMETS","ORNITHISCHIEN","ORNITHISCHIENS","ORNITHORYNQUE","ORNITHORYNQUES","ORPHIE","ORPHIES","ORQUE","ORQUES","ORTOLAN","ORTOLANS",
    "ORVET","ORVETS","ORYCTEROPE","ORYCTEROPES","ORYX","OSCABRION","OSCABRIONS","OSCAR","OSCARS","OSCINE","OSCINES","OSTRACODE","OSTRACODES",
    "OTARIE","OTARIES","OTOCYON","OTOCYONS","OUANANICHE","OUANANICHES","OUAOUARON","OUAOUARONS","OUARINE","OUARINES","OUASSOU","OUASSOUS",
    "OUISTITI","OUISTITIS","OUREBI","OUREBIS","OURS","OURSE","OURSES","OURSIN","OURSINS","OURSON","OURSONNE","OURSONNES","OURSONS","OUTARDE",
    "OUTARDEAU","OUTARDEAUX","OUTARDES","OVIBOS","OVICAPRE","OVICAPRES","OYE","OYES","PACA","PACAS","PACHYURE","PACHYURES","PAGEL","PAGELLE",
    "PAGELLES","PAGELS","PAGEOT","PAGEOTS","PAGRE","PAGRES","PAGURE","PAGURES","PAISSE","PAISSES","PALEMON","PALEMONS","PALETTE","PALETTES",
    "PALMISTE","PALMISTES","PALOMBE","PALOMBES","PALOMINO","PALOMINOS","PALOURDE","PALOURDES","PALUDINE","PALUDINES","PANDA","PANDAS","PANGOLIN",
    "PANGOLINS","PANTHERE","PANTHERES","PANURE","PANURES","PAON","PAONNE","PAONNEAU","PAONNEAUX","PAONNES","PAONS","PAPE","PAPES","PAPION",
    "PAPIONS","PARADISIER","PARADISIERS","PARESSEUX","PARULINE","PARULINES","PASSERINE","PASSERINES","PASSERINETTE","PASSERINETTES","PASTENAGUE",
    "PASTENAGUES","PATAS","PATELLE","PATELLES","PATOU","PATOUS","PAUMIER","PAUMIERS","PECARI","PECARIS","PECTEN","PECTENS","PEGASE","PEGASES",
    "PEIGNE","PEIGNES","PEKAN","PEKANS","PEKINOIS","PELAGIE","PELAGIES","PELAMIDE","PELAMIDES","PELERIN","PELERINE","PELERINES","PELERINS",
    "PELIADE","PELIADES","PELICAN","PELICANS","PELOBATE","PELOBATES","PELODYTE","PELODYTES","PENELOPE","PENELOPES","PERAMELE","PERAMELES","PERCHAUDE",
    "PERCHAUDES","PERCHE","PERCHERON","PERCHERONS","PERCHES","PERDREAU","PERDREAUX","PERDRIX","PERIPATE","PERIPATES","PERLON","PERLONS",
    "PERLOT","PERLOTS","PERROQUET","PERROQUETS","PERRUCHE","PERRUCHES","PERSAN","PERSANS","PETAURE","PETAURES","PETAURISTE","PETAURISTES",
    "PETONCLE","PETONCLES","PETREL","PETRELS","PETROGALE","PETROGALES","PHACOCHERE","PHACOCHERES","PHAETON","PHAETONS","PHALANGER","PHALANGERS",
    "PHALAROPE","PHALAROPES","PHASCOLOME","PHASCOLOMES","PHOLADE","PHOLADES","PHOQUE","PHOQUES","PHRAGMITE","PHRAGMITES","PHYSE","PHYSES","PIBALE",
    "PIBALES","PIC","PICAREL","PICARELS","PICS","PICVERT","PICVERTS","PIE","PIERRETTE","PIERRETTES","PIERROT","PIERROTS","PIES","PIETRAIN",
    "PIETRAINS","PIEUVRE","PIEUVRES","PIGEON","PIGEONNE","PIGEONNEAU","PIGEONNEAUX","PIGEONNES","PIGEONS","PILCHARD","PILCHARDS","PILET","PILETS",
    "PINGOUIN","PINGOUINS","PINNE","PINNES","PINNOTHERE","PINNOTHERES","PINSCHER","PINSCHERS","PINSON","PINSONS","PINTADE","PINTADEAU","PINTADEAUX",
    "PINTADES","PINTADINE","PINTADINES","PIPA","PIPAS","PIPI","PIPIS","PIPISTRELLE","PIPISTRELLES","PIPIT","PIPITS","PIRANHA","PIRANHAS","PIRAYA",
    "PIRAYAS","PITBULL","PITBULLS","PITPIT","PITPITS","PITTA","PITTAS","PIVERT","PIVERTS","PLANCTON","PLANCTONS","PLANORBE","PLANORBES","PLATANISTE",
    "PLATANISTES","PLEUREUR","PLEUREURS","PLEURODELE","PLEURODELES","PLIE","PLIES","PLIOSAURE","PLIOSAURES","PLONGEON","PLONGEONS","PLUVIAN",
    "PLUVIANS","PLUVIER","PLUVIERS","POINTER","POINTERS","POISSON","POISSONS","POITEVIN","POITEVINS","POLATOUCHE","POLATOUCHES","POLYPTERE","POLYPTERES",
    "PONETTE","PONETTES","PONEY","PONEYS","PORC","PORCELAINE","PORCELAINES","PORCELET","PORCELETS","PORCS","PORTUGAISE","PORTUGAISES","PORTUNE",
    "PORTUNES","POTAMOCHERE","POTAMOCHERES","POTOROU","POTOROUS","POTTO","POTTOCK","POTTOCKS","POTTOK","POTTOKS","POTTOS","POUILLARD","POUILLARDS",
    "POUILLOT","POUILLOTS","POULAIN","POULAINE","POULAINES","POULAINS","POULAMON","POULAMONS","POULARDE","POULARDES","POULE","POULES","POULET","POULETS",
    "POULETTE","POULETTES","POULICHE","POULICHES","POULINE","POULINES","POULINIERE","POULINIERES","POULPE","POULPES","POUPART","POUPARTS","POURCEAU",
    "POURCEAUX","POUSSIN","POUSSINE","POUSSINES","POUSSINS","PRAIRE","PRAIRES","PRETRE","PRETRES","PRIODONTE","PRIODONTES","PRION","PRIONS","PROPITHEQUE",
    "PROPITHEQUES","PROTEE","PROTEES","PROTELE","PROTELES","PROTOPTERE","PROTOPTERES","PROYER","PROYERS","PUFFIN","PUFFINS","PUMA","PUMAS","PUTOIS",
    "PYGARGUE","PYGARGUES","PYGMEE","PYGMEES","PYTHON","PYTHONS","QUAHOG","QUAHOGS","QUELEA","QUELEAS","QUETZAL","QUETZALES","QUETZALS","QUISCALE",
    "QUISCALES","RACOON","RACOONS","RAGONDIN","RAGONDINS","RAGOT","RAGOTS","RAIE","RAIES","RAINETTE","RAINETTES","RALE","RALES","RAMEREAU","RAMEREAUX",
    "RAMEROT","RAMEROTS","RAMIER","RAMIERS","RAPIETTE","RAPIETTES","RASCASSE","RASCASSES","RAT","RATE","RATEL","RATELS","RATES","RATIER","RATIERS",
    "RATON","RATONS","RATS","REGALEC","REGALECS","REMIZ","REMORA","REMORAS","RENARD","RENARDE","RENARDEAU","RENARDEAUX","RENARDES","RENARDS","RENNE",
    "RENNES","REQUIN","REQUINS","RETRIEVER","RETRIEVERS","REVERCHON","REVERCHONS","RHENAN","RHENANS","RHESUS","RHINOCEROS","RHINOLOPHE","RHINOLOPHES",
    "RHIZOSTOME","RHIZOSTOMES","RHYNCHOCEPHALE","RHYNCHOCEPHALES","RHYTINE","RHYTINES","RIEUSE","RIEUSES","ROCHIER","ROCHIERS","ROITELET","ROITELETS",
    "ROLLIER","ROLLIERS","ROMAIN","ROMAINS","RONDELLE","RONDELLES","RONDIN","RONDINS","ROQUET","ROQUETS","RORQUAL","RORQUALS","ROSALBIN","ROSALBINS",
    "ROSELET","ROSELETS","ROSELIN","ROSELINS","ROSETTE","ROSETTES","ROSSIGNOL","ROSSIGNOLS","ROTANGLE","ROTANGLES","ROTENGLE","ROTENGLES","ROTTWEILER",
    "ROTTWEILERS","ROTTWEILLER","ROTTWEILLERS","ROUGET","ROUGETS","ROUSSEAU","ROUSSEAUX","ROUSSEROLE","ROUSSEROLES","ROUSSEROLLE","ROUSSEROLLES",
    "ROUSSETTE","ROUSSETTES","RUBIETTE","RUBIETTES","RUBIS","RUPICOLE","RUPICOLES","RUSSE","RUSSES","SAANEN","SAANENS","SABELLE","SABELLES","SABRE",
    "SABRES","SACCULINE","SACCULINES","SACRE","SACRES","SACRET","SACRETS","SAFARI","SAFARIS","SAGOUIN","SAGOUINS","SAI","SAIGA","SAIGAS","SAIMIRI",
    "SAIMIRIS","SAIS","SAJOU","SAJOUS","SAKI","SAKIS","SALAMANDRE","SALAMANDRES","SALANGANE","SALANGANES","SALERS","SALICOQUE","SALICOQUES","SALPE",
    "SALPES","SAMOYEDE","SAMOYEDES","SANDERLING","SANDERLINGS","SANDRE","SANDRES","SANGLIER","SANGLIERS","SANGSUE","SANGSUES","SANSONNET","SANSONNETS",
    "SAOLA","SAOLAS","SAPAJOU","SAPAJOUS","SAPHIR","SAPHIRS","SAR","SARCELLE","SARCELLES","SARDINE","SARDINELLE","SARDINELLES","SARDINES","SARGUE",
    "SARGUES","SARIGUE","SARIGUES","SARS","SASSA","SASSAS","SAUMON","SAUMONEAU","SAUMONEAUX","SAUMONETTE","SAUMONETTES","SAUMONS","SAUPE","SAUPES",
    "SAUREL","SAURELS","SAUROPODE","SAUROPODES","SAVON","SAVONS","SCALAIRE","SCALAIRES","SCAMPI","SCAMPIS","SCARE","SCARES","SCHIPPERKE","SCHIPPERKES",
    "SCHNAUZER","SCHNAUZERS","SCIENE","SCIENES","SCINQUE","SCINQUES","SCONSE","SCONSES","SCORPENE","SCORPENES","SCORPION","SCORPIONS","SEBASTE",
    "SEBASTES","SECHE","SECHES","SECRETAIRE","SECRETAIRES","SEICHE","SEICHES","SEMNOPITHEQUE","SEMNOPITHEQUES","SENEGALI","SENEGALIS","SENTINELLE",
    "SENTINELLES","SEPIOLE","SEPIOLES","SEPS","SERIN","SERINE","SERINES","SERINS","SERIOLE","SERIOLES","SEROTINE","SEROTINES","SERPENT","SERPENTAIRE",
    "SERPENTAIRES","SERPENTEAU","SERPENTEAUX","SERPENTS","SERPULE","SERPULES","SERRAN","SERRANS","SERVAL","SERVALS","SETTER","SETTERS","SHAMA",
    "SHAMAS","SHARPEI","SHARPEIS","SHETLAND","SHETLANDS","SIAMANG","SIAMANGS","SIAMOIS","SIBERIEN","SIBERIENS","SIFFLEUR","SIFFLEURS","SIFFLEUX",
    "SIFILET","SIFILETS","SILURE","SILURES","SIMMENTAL","SIMMENTALS","SINGE","SINGES","SIRENE","SIRENES","SIRLI","SIRLIS","SITTELE","SITTELES",
    "SITTELLE","SITTELLES","SIZERIN","SIZERINS","SKONS","SKUA","SKUAS","SKUNKS","SKUNS","SLOUGHI","SLOUGHIS","SMOLT","SMOLTS","SOLE","SOLEN","SOLENS",
    "SOLES","SOLETTE","SOLETTES","SOLITAIRE","SOLITAIRES","SOMALI","SOMALIS","SOUCHET","SOUCHETS","SOUIMANGA","SOUIMANGAS","SOULCIE","SOULCIES",
    "SOURD","SOURDE","SOURDES","SOURDS","SOURICEAU","SOURICEAUX","SOURIS","SOUSLIK","SOUSLIKS","SPALAX","SPATANGUE","SPATANGUES","SPATULE","SPATULES",
    "SPERMOPHILE","SPERMOPHILES","SPET","SPETS","SPHENODON","SPHENODONS","SPHYRENE","SPHYRENES","SPIONCELLE","SPIONCELLES","SPITZ","SPONDYLE",
    "SPONDYLES","SPONGILLE","SPONGILLES","SPRAT","SPRATS","SPRINGBOK","SPRINGBOKS","SPRINGER","SPRINGERS","SQUALE","SQUALES","SQUATINA","SQUATINAS",
    "SQUATINE","SQUATINES","SQUILLE","SQUILLES","STEENBOK","STEENBOKS","STEGOSAURE","STEGOSAURES","STEINBOCK","STEINBOCKS","STENO","STENOS","STERLET",
    "STERLETS","STERNE","STERNES","STRIX","STROMBE","STROMBES","SUCRIER","SUCRIERS","SUEDOIS","SUFFOLK","SUFFOLKS","SUISSE","SUISSES","SUPION",
    "SUPIONS","SURICATE","SURICATES","SURIKATE","SURIKATES","SURMULET","SURMULETS","SURMULOT","SURMULOTS","SYRRHAPTE","SYRRHAPTES","TACAUD","TACAUDS",
    "TACON","TACONS","TADORNE","TADORNES","TAENIA","TAENIAS","TAGAL","TAGALS","TALAPOIN","TALAPOINS","TALITRE","TALITRES","TAMANDUA","TAMANDUAS",
    "TAMANOIR","TAMANOIRS","TAMARIN","TAMARINS","TAMIA","TAMIAS","TANCHE","TANCHES","TANGARA","TANGARAS","TANREC","TANRECS","TANTALE","TANTALES","TAPIR",
    "TAPIRS","TAPON","TAPONS","TARENTE","TARENTES","TARENTULE","TARENTULES","TARET","TARETS","TARIN","TARINE","TARINES","TARINS","TARPAN","TARPANS",
    "TARPON","TARPONS","TARSIER","TARSIERS","TATOU","TATOUS","TAUPE","TAUPES","TAURE","TAUREAU","TAUREAUX","TAURES","TAURILLON","TAURILLONS","TAURIN",
    "TAURINS","TECKEL","TECKELS","TEGENAIRE","TEGENAIRES","TEJU","TEJUS","TELLINE","TELLINES","TENIA","TENIAS","TENREC","TENRECS","TEREBRATULE","TEREBRATULES",
    "TERRIER","TERRIERS","TERVUEREN","TERVUERENS","TESTACELLE","TESTACELLES","TETARD","TETARDS","TETRA","TETRAS","TETRODON","TETRODONS","THAI","THAIS",
    "THAZARD","THAZARDS","THIOF","THIOFS","THOMISE","THOMISES","THON","THONINE","THONINES","THONS","THYLACINE","THYLACINES","TICHODROME","TICHODROMES",
    "TIERCELET","TIERCELETS","TIGLON","TIGLONS","TIGRE","TIGRES","TIGRESSE","TIGRESSES","TIGRON","TIGRONS","TILAPIA","TILAPIAS","TINAMOU","TINAMOUS",
    "TIQUE","TIQUES","TISSERIN","TISSERINS","TITI","TITIS","TOBY","TOBYS","TONKINOIS","TOPAZE","TOPAZES","TORCOL","TORCOLS","TORCOU","TORCOUS","TORPILLE",
    "TORPILLES","TORTUE","TORTUES","TOUCAN","TOUCANS","TOUILLE","TOUILLES","TOULADI","TOULADIS","TOUPAYE","TOUPAYES","TOURACO","TOURACOS","TOURD","TOURDE",
    "TOURDES","TOURDS","TOURNEPIERRE","TOURNEPIERRES","TOURTE","TOURTEAU","TOURTEAUX","TOURTEREAU","TOURTEREAUX","TOURTERELLE","TOURTERELLES","TOURTES",
    "TRANCHOIR","TRANCHOIRS","TRAQUET","TRAQUETS","TRAVAILLEUR","TRAVAILLEURS","TREPANG","TREPANGS","TRIALLE","TRIALLES","TRICERATOPS","TRIDACNE",
    "TRIDACNES","TRIGLE","TRIGLES","TRIONYX","TRIPANG","TRIPANGS","TRITON","TRITONS","TROCHE","TROCHES","TROQUE","TROQUES","TROTTEUR","TROTTEURS",
    "TROUPIALE","TROUPIALES","TRUIE","TRUIES","TRUITE","TRUITELLE","TRUITELLES","TRUITES","TUPAIA","TUPAIAS","TUPAJA","TUPAJAS","TUPINAMBIS","TURBINELLE",
    "TURBINELLES","TURBO","TURBOS","TURBOT","TURBOTIN","TURBOTINS","TURBOTS","TURQUIN","TURQUINS","TYRAN","TYRANNEAU","TYRANNEAUX","TYRANNOSAURE",
    "TYRANNOSAURES","TYRANS","UKRAINIEN","UKRAINIENS","UNAU","UNAUS","UNAUX","URAETE","URAETES","URANOSCOPE","URANOSCOPES","URE","URES","URODELE",
    "URODELES","UROPYGE","UROPYGES","URUBU","URUBUS","URUS","VACHE","VACHES","VACHETTE","VACHETTES","VACIVE","VACIVES","VAIRON","VAIRONS","VAMPIRE",
    "VAMPIRES","VANDOISE","VANDOISES","VANNEAU","VANNEAUX","VARAN","VARANS","VASSIVEAU","VASSIVEAUX","VAUTOUR","VAUTOURS","VEAU","VEAUX","VELELLE",
    "VELELLES","VELLE","VELLES","VELOCIRAPTOR","VELOCIRAPTORS","VENDANGETTE","VENDANGETTES","VENERICARDE","VENERICARDES","VENGERON","VENGERONS","VENTURON",
    "VENTURONS","VENUS","VER","VERDIER","VERDIERS","VERDIN","VERDINS","VERMET","VERMETS","VERMISSEAU","VERMISSEAUX","VERRAT","VERRATS","VERS","VERVET",
    "VERVETS","VESPERTILION","VESPERTILIONS","VEUVE","VEUVES","VIEILLE","VIEILLES","VIGNEAU","VIGNEAUX","VIGNOT","VIGNOTS","VIGOGNE","VIGOGNES","VIOLET",
    "VIOLETS","VIPERE","VIPEREAU","VIPEREAUX","VIPERES","VIPERIAU","VIPERIAUX","VISCACHE","VISCACHES","VISON","VISONS","VITRINE","VITRINES","VIVANEAU",
    "VIVANEAUX","VIVE","VIVES","VOILIER","VOILIERS","VOLUTE","VOLUTES","WALLABIES","WALLABY","WALLABYS","WAPITI","WAPITIS","WESTIE","WESTIES","WESTPHALIEN",
    "WESTPHALIENS","WHIPPET","WHIPPETS","WOMBAT","WOMBATS","WYANDOTTE","WYANDOTTES","XENARTHRE","XENARTHRES","XENOPE","XENOPES","XERUS","XIPHO",
    "XIPHOPHORE","XIPHOPHORES","XIPHOS","YACK","YACKS","YAK","YAKS","YAPOCK","YAPOCKS","YAPOK","YAPOKS","YEARLING","YEARLINGS","YET","YETS","YORKSHIRE",
    "YORKSHIRES","ZANCLE","ZANCLES","ZEBRE","ZEBRES","ZEBU","ZEBUS","ZEE","ZEES","ZIBELINE","ZIBELINES","ZIZI","ZIZIS","ZOE","ZOES","ZONURE","ZONURES",
    "ZORILLE","ZORILLES","ZOSTEROPS","ZYGENE","ZYGENES"]
    ]
    ]]
];

