const DATA_FRENCH_TERRITORY = {
    id : "LIEU_FRANCE_TERRITOIRE",
    labels : {region_code: 0, code: 1, departement: 2, region: 3},
    data : [
["84","1","ain", "auvergne rhône-alpes"],
["32","2","aisne", "hauts de france"],
["84","3","allier", "auvergne rhône-alpes"],
["93","4","alpes-de-haute-provence", "provence-alpes-côte d'azur"],
["93","5","hautes-alpes", "provence-alpes-côte d'azur"],
["93","6","alpes-maritimes", "provence-alpes-côte d'azur"],
["84","7","ardèche", "auvergne rhône-alpes"],
["44","8","ardennes", "grand-est"],
["76","9","ariège", "occitanie"],
["44","10","aube", "grand-est"],
["76","11","aude", "occitanie"],
["76","12","aveyron", "occitanie"],
["93","13","bouches-du-rhône", "provence-alpes-côte d'azur"],
["28","14","calvados", "normandie"],
["84","15","cantal", "auvergne rhône-alpes"],
["75","16","charente", "nouvelle aquitaine"],
["75","17","charente-maritime", "nouvelle aquitaine"],
["24","18","cher", "centre val de loire"],
["75","19","corrèze", "nouvelle aquitaine"],
["27","21","côte-d'or", "bourgogne franche-comté"],
["53","22","côtes-d'armor", "bretagne"],
["75","23","creuse", "nouvelle aquitaine"],
["75","24","dordogne", "nouvelle aquitaine"],
["27","25","doubs", "bourgogne franche-comté"],
["84","26","drôme", "auvergne rhône-alpes"],
["28","27","eure", "normandie"],
["24","28","eure-et-loir", "centre val de loire"],
["53","29","finistère", "bretagne"],
["94","2a","corse-du-sud", "corse"],
["94","2b","haute-corse", "corse"],
["76","30","gard", "occitanie"],
["76","31","haute-garonne", "occitanie"],
["76","32","gers", "occitanie"],
["75","33","gironde", "nouvelle aquitaine"],
["76","34","hérault", "occitanie"],
["53","35","ille-et-vilaine", "bretagne"],
["24","36","indre", "centre val de loire"],
["24","37","indre-et-loire", "centre val de loire"],
["84","38","isère", "auvergne rhône-alpes"],
["27","39","jura", "bourgogne franche-comté"],
["75","40","landes", "nouvelle aquitaine"],
["24","41","loir-et-cher", "centre val de loire"],
["84","42","loire", "auvergne rhône-alpes"],
["84","43","haute-loire", "auvergne rhône-alpes"],
["52","44","loire-atlantique", "pays de la loire"],
["24","45","loiret", "centre val de loire"],
["76","46","lot", "occitanie"],
["75","47","lot-et-garonne", "nouvelle aquitaine"],
["76","48","lozère", "occitanie"],
["52","49","maine-et-loire", "pays de la loire"],
["28","50","manche", "normandie"],
["44","51","marne", "grand-est"],
["44","52","haute-marne", "grand-est"],
["52","53","mayenne", "pays de la loire"],
["44","54","meurthe-et-moselle", "grand-est"],
["44","55","meuse", "grand-est"],
["53","56","morbihan", "bretagne"],
["44","57","moselle", "grand-est"],
["27","58","nièvre", "bourgogne franche-comté"],
["32","59","nord", "hauts de france"],
["32","60","oise", "hauts de france"],
["28","61","orne", "normandie"],
["32","62","pas-de-calais", "hauts de france"],
["84","63","puy-de-dôme", "auvergne rhône-alpes"],
["75","64","pyrénées-atlantiques", "nouvelle aquitaine"],
["76","65","hautes-pyrénées", "occitanie"],
["76","66","pyrénées-orientales", "occitanie"],
["44","67","bas-rhin", "grand-est"],
["44","68","haut-rhin", "grand-est"],
["84","69","rhône", "auvergne rhône-alpes"],
["27","70","haute-saône", "bourgogne franche-comté"],
["27","71","saône-et-loire", "bourgogne franche-comté"],
["52","72","sarthe", "pays de la loire"],
["84","73","savoie", "auvergne rhône-alpes"],
["84","74","haute-savoie", "auvergne rhône-alpes"],
["11","75","paris", "île-de-france"],
["28","76","seine-maritime", "normandie"],
["11","77","seine-et-marne", "île-de-france"],
["11","78","yvelines", "île-de-france"],
["75","79","deux-sèvres", "nouvelle aquitaine"],
["32","80","somme", "hauts de france"],
["76","81","tarn", "occitanie"],
["76","82","tarn-et-garonne", "occitanie"],
["93","83","var", "provence-alpes-côte d'azur"],
["93","84","vaucluse", "provence-alpes-côte d'azur"],
["52","85","vendée", "pays de la loire"],
["75","86","vienne", "nouvelle aquitaine"],
["75","87","haute-vienne", "nouvelle aquitaine"],
["44","88","vosges", "grand-est"],
["27","89","yonne", "bourgogne franche-comté"],
["27","90","territoire de belfort", "bourgogne franche-comté"],
["11","91","essonne", "île-de-france"],
["11","92","hauts-de-seine", "île-de-france"],
["11","93","seine-saint-denis", "île-de-france"],
["11","94","val-de-marne", "île-de-france"],
["11","95","val-d'oise", "île-de-france"],
["1","971","guadeloupe", "guadeloupe"],
["2","972","martinique", "martinique"],
["3","973","guyane", "guyane"],
["4","974","la réunion", "la réunion"],
["6","976","mayotte", "mayotte"],
["com","975","saint-pierre-et-miquelon", "saint-pierre-et-miquelon"],
["com","977","saint-barthélemy", "saint-barthélemy"],
["com","978","saint-martin", "saint-martin"],
["com","984","terres australes et antarctiques françaises", "terres australes et antarctiques françaises"],
["com","986","wallis et futuna", "wallis et futuna"],
["com","987","polynésie française", "polynésie française"],
["com","988","nouvelle-calédonie", "nouvelle-calédonie"],
["com","989","île de clipperton", "île de clipperton"],
]};